// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: esp32-kitchen-timer

#include "ui.h"

lv_obj_t * ui_scrTimers = NULL;
lv_obj_t * ui_panTempHeader = NULL;
lv_obj_t * ui_imgTempHome = NULL;
lv_obj_t * ui_lblTempHeader = NULL;
lv_obj_t * ui_imgTempHeaderVol = NULL;
lv_obj_t * ui_contTempAll = NULL;
lv_obj_t * ui_contTempRow1 = NULL;
lv_obj_t * ui_contTempTemp1 = NULL;
lv_obj_t * ui_lblTempTimer1Time = NULL;
lv_obj_t * ui_lblTempTimer1Count = NULL;
lv_obj_t * ui_imgTempTimer1Chrono = NULL;
lv_obj_t * ui_panTempTemp1Add = NULL;
lv_obj_t * ui_imgTempTemp1AddTimer = NULL;
lv_obj_t * ui_imgTempTemp1AddChrono = NULL;
lv_obj_t * ui_panTempTemp1Control = NULL;
lv_obj_t * ui_imgTempTemp1Play = NULL;
lv_obj_t * ui_imgTempTemp1Stop = NULL;
lv_obj_t * ui_contTempTemp2 = NULL;
lv_obj_t * ui_lblTempTimer2Time = NULL;
lv_obj_t * ui_lblTempTimer2Count = NULL;
lv_obj_t * ui_imgTempTimer2Chrono = NULL;
lv_obj_t * ui_panTempTemp2Add = NULL;
lv_obj_t * ui_imgTempTemp2AddTimer = NULL;
lv_obj_t * ui_imgTempTemp2AddChrono = NULL;
lv_obj_t * ui_panTempTemp2Control = NULL;
lv_obj_t * ui_imgTempTemp2Play = NULL;
lv_obj_t * ui_imgTempTemp2Stop = NULL;
lv_obj_t * ui_contTempRow2 = NULL;
lv_obj_t * ui_contTempTemp3 = NULL;
lv_obj_t * ui_lblTempTimer3Time = NULL;
lv_obj_t * ui_lblTempTimer3Count = NULL;
lv_obj_t * ui_imgTempTimer3Chrono = NULL;
lv_obj_t * ui_panTempTemp3Add = NULL;
lv_obj_t * ui_imgTempTemp3AddTimer = NULL;
lv_obj_t * ui_imgTempTemp3AddChrono = NULL;
lv_obj_t * ui_panTempTemp3Control = NULL;
lv_obj_t * ui_imgTempTemp3Play = NULL;
lv_obj_t * ui_imgTempTemp3Stop = NULL;
lv_obj_t * ui_contTempTemp4 = NULL;
lv_obj_t * ui_lblTempTimer4Time = NULL;
lv_obj_t * ui_lblTempTimer4Count = NULL;
lv_obj_t * ui_imgTempTimer4Chrono = NULL;
lv_obj_t * ui_panTempTemp4Add = NULL;
lv_obj_t * ui_imgTempTemp4AddTimer = NULL;
lv_obj_t * ui_imgTempTemp4AddChrono = NULL;
lv_obj_t * ui_panTempTemp4Control = NULL;
lv_obj_t * ui_imgTempTemp4Play = NULL;
lv_obj_t * ui_imgTempTemp4Stop = NULL;
lv_obj_t * ui_panTempSound = NULL;
lv_obj_t * ui_conTempSoundHigh = NULL;
lv_obj_t * ui_contTempSoundTheme = NULL;
lv_obj_t * ui_lblTempSoundTheme = NULL;
lv_obj_t * ui_rollSoundTheme = NULL;
lv_obj_t * ui_contTempSoundVolume = NULL;
lv_obj_t * ui_lblTempSoundVolume = NULL;
lv_obj_t * ui_sldTempSoundVolume = NULL;
lv_obj_t * ui_conTempSoundBtn = NULL;
lv_obj_t * ui_btnTempSoundOk = NULL;
lv_obj_t * ui_lblTempSoundOk = NULL;
// event funtions
void ui_event_imgTempHome(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrMain, LV_SCR_LOAD_ANIM_NONE, 250, 0, &ui_scrMain_screen_init);
    }
}

void ui_event_imgTempHeaderVol(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_panTempSound, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_imgTempTemp1AddTimer(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_label_set_property(ui_lblTempNewHeader, _UI_LABEL_PROPERTY_TEXT, "TEMPORIZADOR 1");
        _ui_screen_change(&ui_scrNewTimer, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_scrNewTimer_screen_init);
    }
}

void ui_event_imgTempTemp1AddChrono(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        imgTempTemp1AddChronoClick(e);
    }
}

void ui_event_imgTempTemp1Play(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        imgTempTemp1PlayClick(e);
    }
}

void ui_event_imgTempTemp1Stop(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        imgTempTemp1StopClick(e);
    }
}

void ui_event_imgTempTemp2AddTimer(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_label_set_property(ui_lblTempNewHeader, _UI_LABEL_PROPERTY_TEXT, "TEMPORIZADOR 2");
        _ui_screen_change(&ui_scrNewTimer, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_scrNewTimer_screen_init);
    }
}

void ui_event_imgTempTemp2AddChrono(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        imgTempTemp2AddChronoClick(e);
    }
}

void ui_event_imgTempTemp2Play(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        imgTempTemp2PlayClick(e);
    }
}

void ui_event_imgTempTemp2Stop(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        imgTempTemp2StopClick(e);
    }
}

void ui_event_imgTempTemp3AddTimer(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_label_set_property(ui_lblTempNewHeader, _UI_LABEL_PROPERTY_TEXT, "TEMPORIZADOR 3");
        _ui_screen_change(&ui_scrNewTimer, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_scrNewTimer_screen_init);
    }
}

void ui_event_imgTempTemp3AddChrono(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        imgTempTemp3AddChronoClick(e);
    }
}

void ui_event_imgTempTemp3Play(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        imgTempTemp3PlayClick(e);
    }
}

void ui_event_imgTempTemp3Stop(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        imgTempTemp3StopClick(e);
    }
}

void ui_event_imgTempTemp4AddTimer(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_label_set_property(ui_lblTempNewHeader, _UI_LABEL_PROPERTY_TEXT, "TEMPORIZADOR 4");
        _ui_screen_change(&ui_scrNewTimer, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_scrNewTimer_screen_init);
    }
}

void ui_event_imgTempTemp4AddChrono(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        imgTempTemp4AddChronoClick(e);
    }
}

void ui_event_imgTempTemp4Play(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        imgTempTemp4PlayClick(e);
    }
}

void ui_event_imgTempTemp4Stop(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        imgTempTemp4StopClick(e);
    }
}

void ui_event_rollSoundTheme(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        rollSoundThemeChanged(e);
    }
}

void ui_event_sldTempSoundVolume(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        sldTempSoundVolumeChange(e);
    }
    if(event_code == LV_EVENT_RELEASED) {
        sldTempSoundVolumeRelease(e);
    }
}

void ui_event_btnTempSoundOk(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_panTempSound, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

// build funtions

void ui_scrTimers_screen_init(void)
{
    ui_scrTimers = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_scrTimers, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_scrTimers, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panTempHeader = lv_obj_create(ui_scrTimers);
    lv_obj_set_height(ui_panTempHeader, 40);
    lv_obj_set_width(ui_panTempHeader, lv_pct(100));
    lv_obj_set_flex_flow(ui_panTempHeader, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_panTempHeader, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_panTempHeader, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_panTempHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panTempHeader, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panTempHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_panTempHeader, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgTempHome = lv_imagebutton_create(ui_panTempHeader);
    lv_imagebutton_set_src(ui_imgTempHome, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_home_png, NULL);
    lv_imagebutton_set_src(ui_imgTempHome, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_home_png, NULL);
    lv_obj_set_width(ui_imgTempHome, 32);
    lv_obj_set_height(ui_imgTempHome, 32);
    lv_obj_set_align(ui_imgTempHome, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_imgTempHome, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_IMAGE_RECOLOR,
                                           _ui_theme_color_colorTimerDef);
    ui_object_set_themeable_style_property(ui_imgTempHome, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_IMAGE_RECOLOR_OPA,
                                           _ui_theme_alpha_colorTimerDef);

    ui_lblTempHeader = lv_label_create(ui_panTempHeader);
    lv_obj_set_width(ui_lblTempHeader, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTempHeader, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblTempHeader, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_lblTempHeader, "TEMPORIZADORES");
    lv_obj_set_style_pad_left(ui_lblTempHeader, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblTempHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblTempHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblTempHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgTempHeaderVol = lv_image_create(ui_panTempHeader);
    lv_image_set_src(ui_imgTempHeaderVol, &ui_img_volume_mid_png);
    lv_obj_set_width(ui_imgTempHeaderVol, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgTempHeaderVol, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgTempHeaderVol, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgTempHeaderVol, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgTempHeaderVol, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_imgTempHeaderVol, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_IMAGE_RECOLOR,
                                           _ui_theme_color_colorTimerDef);
    ui_object_set_themeable_style_property(ui_imgTempHeaderVol, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_IMAGE_RECOLOR_OPA,
                                           _ui_theme_alpha_colorTimerDef);

    ui_contTempAll = lv_obj_create(ui_scrTimers);
    lv_obj_remove_style_all(ui_contTempAll);
    lv_obj_set_height(ui_contTempAll, 435);
    lv_obj_set_width(ui_contTempAll, lv_pct(100));
    lv_obj_set_align(ui_contTempAll, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_set_flex_flow(ui_contTempAll, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_contTempAll, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contTempAll, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_contTempRow1 = lv_obj_create(ui_contTempAll);
    lv_obj_remove_style_all(ui_contTempRow1);
    lv_obj_set_width(ui_contTempRow1, lv_pct(100));
    lv_obj_set_flex_grow(ui_contTempRow1, 1);
    lv_obj_set_x(ui_contTempRow1, 0);
    lv_obj_set_y(ui_contTempRow1, 32);
    lv_obj_set_align(ui_contTempRow1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_contTempRow1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_contTempRow1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contTempRow1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_contTempTemp1 = lv_obj_create(ui_contTempRow1);
    lv_obj_remove_style_all(ui_contTempTemp1);
    lv_obj_set_height(ui_contTempTemp1, lv_pct(100));
    lv_obj_set_flex_grow(ui_contTempTemp1, 1);
    lv_obj_set_align(ui_contTempTemp1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contTempTemp1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_contTempTemp1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_colorTimerDef);
    ui_object_set_themeable_style_property(ui_contTempTemp1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_colorTimerDef);
    lv_obj_set_style_border_width(ui_contTempTemp1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_contTempTemp1, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTempTimer1Time = lv_label_create(ui_contTempTemp1);
    lv_obj_set_width(ui_lblTempTimer1Time, 100);
    lv_obj_set_height(ui_lblTempTimer1Time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblTempTimer1Time, 10);
    lv_obj_set_y(ui_lblTempTimer1Time, 10);
    lv_label_set_text(ui_lblTempTimer1Time, "--:--");
    lv_obj_set_style_text_align(ui_lblTempTimer1Time, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_lblTempTimer1Time, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_lblTempTimer1Time, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_colorTimerDef);
    ui_object_set_themeable_style_property(ui_lblTempTimer1Time, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_colorTimerDef);

    ui_lblTempTimer1Count = lv_label_create(ui_contTempTemp1);
    lv_obj_set_width(ui_lblTempTimer1Count, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTempTimer1Count, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblTempTimer1Count, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblTempTimer1Count, "--:--");
    ui_object_set_themeable_style_property(ui_lblTempTimer1Count, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_colorTimerDef);
    ui_object_set_themeable_style_property(ui_lblTempTimer1Count, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_colorTimerDef);
    lv_obj_set_style_text_font(ui_lblTempTimer1Count, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblTempTimer1Count, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblTempTimer1Count, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblTempTimer1Count, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblTempTimer1Count, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgTempTimer1Chrono = lv_image_create(ui_contTempTemp1);
    lv_image_set_src(ui_imgTempTimer1Chrono, &ui_img_timer_png);
    lv_obj_set_width(ui_imgTempTimer1Chrono, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgTempTimer1Chrono, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imgTempTimer1Chrono, -10);
    lv_obj_set_y(ui_imgTempTimer1Chrono, 10);
    lv_obj_set_align(ui_imgTempTimer1Chrono, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_imgTempTimer1Chrono, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgTempTimer1Chrono, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_imgTempTimer1Chrono, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR,
                                           _ui_theme_color_colorTimerDef);
    ui_object_set_themeable_style_property(ui_imgTempTimer1Chrono, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_colorTimerDef);

    ui_panTempTemp1Add = lv_obj_create(ui_contTempTemp1);
    lv_obj_set_height(ui_panTempTemp1Add, 50);
    lv_obj_set_width(ui_panTempTemp1Add, lv_pct(100));
    lv_obj_set_align(ui_panTempTemp1Add, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_panTempTemp1Add, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_panTempTemp1Add, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_panTempTemp1Add, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_panTempTemp1Add, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgTempTemp1AddTimer = lv_imagebutton_create(ui_panTempTemp1Add);
    lv_imagebutton_set_src(ui_imgTempTemp1AddTimer, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_hourglass_bottom_png,
                           NULL);
    lv_imagebutton_set_src(ui_imgTempTemp1AddTimer, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_hourglass_bottom_png, NULL);
    lv_obj_set_width(ui_imgTempTemp1AddTimer, 48);
    lv_obj_set_height(ui_imgTempTemp1AddTimer, 48);
    lv_obj_set_align(ui_imgTempTemp1AddTimer, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_imgTempTemp1AddTimer, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_IMAGE_RECOLOR,
                                           _ui_theme_color_colorTimerDef);
    ui_object_set_themeable_style_property(ui_imgTempTemp1AddTimer, LV_PART_MAIN | LV_STATE_PRESSED,
                                           LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_colorTimerDef);

    ui_imgTempTemp1AddChrono = lv_imagebutton_create(ui_panTempTemp1Add);
    lv_imagebutton_set_src(ui_imgTempTemp1AddChrono, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_timer_png, NULL);
    lv_imagebutton_set_src(ui_imgTempTemp1AddChrono, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_timer_png, NULL);
    lv_obj_set_width(ui_imgTempTemp1AddChrono, 48);
    lv_obj_set_height(ui_imgTempTemp1AddChrono, 48);
    lv_obj_set_align(ui_imgTempTemp1AddChrono, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_imgTempTemp1AddChrono, LV_PART_MAIN | LV_STATE_PRESSED,
                                           LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_colorTimerDef);
    ui_object_set_themeable_style_property(ui_imgTempTemp1AddChrono, LV_PART_MAIN | LV_STATE_PRESSED,
                                           LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_colorTimerDef);

    ui_panTempTemp1Control = lv_obj_create(ui_contTempTemp1);
    lv_obj_set_height(ui_panTempTemp1Control, 50);
    lv_obj_set_width(ui_panTempTemp1Control, lv_pct(100));
    lv_obj_set_align(ui_panTempTemp1Control, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_panTempTemp1Control, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_panTempTemp1Control, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_panTempTemp1Control, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_panTempTemp1Control, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_panTempTemp1Control, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgTempTemp1Play = lv_imagebutton_create(ui_panTempTemp1Control);
    lv_imagebutton_set_src(ui_imgTempTemp1Play, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_pause_png, NULL);
    lv_imagebutton_set_src(ui_imgTempTemp1Play, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_pause_png, NULL);
    lv_imagebutton_set_src(ui_imgTempTemp1Play, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui_img_play_png, NULL);
    lv_imagebutton_set_src(ui_imgTempTemp1Play, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_play_png, NULL);
    lv_obj_set_width(ui_imgTempTemp1Play, 48);
    lv_obj_set_height(ui_imgTempTemp1Play, 48);
    lv_obj_set_align(ui_imgTempTemp1Play, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgTempTemp1Play, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    ui_object_set_themeable_style_property(ui_imgTempTemp1Play, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_IMAGE_RECOLOR,
                                           _ui_theme_color_colorTimerDef);
    ui_object_set_themeable_style_property(ui_imgTempTemp1Play, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_IMAGE_RECOLOR_OPA,
                                           _ui_theme_alpha_colorTimerDef);

    ui_imgTempTemp1Stop = lv_imagebutton_create(ui_panTempTemp1Control);
    lv_imagebutton_set_src(ui_imgTempTemp1Stop, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_stop_png, NULL);
    lv_imagebutton_set_src(ui_imgTempTemp1Stop, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_stop_png, NULL);
    lv_obj_set_width(ui_imgTempTemp1Stop, 48);
    lv_obj_set_height(ui_imgTempTemp1Stop, 48);
    lv_obj_set_align(ui_imgTempTemp1Stop, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_imgTempTemp1Stop, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_IMAGE_RECOLOR,
                                           _ui_theme_color_colorTimerDef);
    ui_object_set_themeable_style_property(ui_imgTempTemp1Stop, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_IMAGE_RECOLOR_OPA,
                                           _ui_theme_alpha_colorTimerDef);

    ui_contTempTemp2 = lv_obj_create(ui_contTempRow1);
    lv_obj_remove_style_all(ui_contTempTemp2);
    lv_obj_set_height(ui_contTempTemp2, lv_pct(100));
    lv_obj_set_flex_grow(ui_contTempTemp2, 1);
    lv_obj_set_align(ui_contTempTemp2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contTempTemp2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_contTempTemp2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_colorTimerDef);
    ui_object_set_themeable_style_property(ui_contTempTemp2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_colorTimerDef);
    lv_obj_set_style_border_width(ui_contTempTemp2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_contTempTemp2, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTempTimer2Time = lv_label_create(ui_contTempTemp2);
    lv_obj_set_width(ui_lblTempTimer2Time, 100);
    lv_obj_set_height(ui_lblTempTimer2Time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblTempTimer2Time, 10);
    lv_obj_set_y(ui_lblTempTimer2Time, 10);
    lv_label_set_text(ui_lblTempTimer2Time, "--:--");
    lv_obj_set_style_text_align(ui_lblTempTimer2Time, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_lblTempTimer2Time, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_lblTempTimer2Time, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_colorTimerDef);
    ui_object_set_themeable_style_property(ui_lblTempTimer2Time, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_colorTimerDef);

    ui_lblTempTimer2Count = lv_label_create(ui_contTempTemp2);
    lv_obj_set_width(ui_lblTempTimer2Count, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTempTimer2Count, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblTempTimer2Count, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblTempTimer2Count, "--:--");
    ui_object_set_themeable_style_property(ui_lblTempTimer2Count, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_colorTimerDef);
    ui_object_set_themeable_style_property(ui_lblTempTimer2Count, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_colorTimerDef);
    lv_obj_set_style_text_font(ui_lblTempTimer2Count, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblTempTimer2Count, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblTempTimer2Count, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblTempTimer2Count, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblTempTimer2Count, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgTempTimer2Chrono = lv_image_create(ui_contTempTemp2);
    lv_image_set_src(ui_imgTempTimer2Chrono, &ui_img_timer_png);
    lv_obj_set_width(ui_imgTempTimer2Chrono, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgTempTimer2Chrono, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imgTempTimer2Chrono, -10);
    lv_obj_set_y(ui_imgTempTimer2Chrono, 10);
    lv_obj_set_align(ui_imgTempTimer2Chrono, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_imgTempTimer2Chrono, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgTempTimer2Chrono, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_imgTempTimer2Chrono, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR,
                                           _ui_theme_color_colorTimerDef);
    ui_object_set_themeable_style_property(ui_imgTempTimer2Chrono, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_colorTimerDef);

    ui_panTempTemp2Add = lv_obj_create(ui_contTempTemp2);
    lv_obj_set_height(ui_panTempTemp2Add, 50);
    lv_obj_set_width(ui_panTempTemp2Add, lv_pct(100));
    lv_obj_set_align(ui_panTempTemp2Add, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_panTempTemp2Add, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_panTempTemp2Add, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_panTempTemp2Add, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_panTempTemp2Add, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgTempTemp2AddTimer = lv_imagebutton_create(ui_panTempTemp2Add);
    lv_imagebutton_set_src(ui_imgTempTemp2AddTimer, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_hourglass_bottom_png,
                           NULL);
    lv_imagebutton_set_src(ui_imgTempTemp2AddTimer, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_hourglass_bottom_png, NULL);
    lv_obj_set_width(ui_imgTempTemp2AddTimer, 48);
    lv_obj_set_height(ui_imgTempTemp2AddTimer, 48);
    lv_obj_set_align(ui_imgTempTemp2AddTimer, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_imgTempTemp2AddTimer, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_IMAGE_RECOLOR,
                                           _ui_theme_color_colorTimerDef);
    ui_object_set_themeable_style_property(ui_imgTempTemp2AddTimer, LV_PART_MAIN | LV_STATE_PRESSED,
                                           LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_colorTimerDef);

    ui_imgTempTemp2AddChrono = lv_imagebutton_create(ui_panTempTemp2Add);
    lv_imagebutton_set_src(ui_imgTempTemp2AddChrono, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_timer_png, NULL);
    lv_imagebutton_set_src(ui_imgTempTemp2AddChrono, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_timer_png, NULL);
    lv_obj_set_width(ui_imgTempTemp2AddChrono, 48);
    lv_obj_set_height(ui_imgTempTemp2AddChrono, 48);
    lv_obj_set_align(ui_imgTempTemp2AddChrono, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_imgTempTemp2AddChrono, LV_PART_MAIN | LV_STATE_PRESSED,
                                           LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_colorTimerDef);
    ui_object_set_themeable_style_property(ui_imgTempTemp2AddChrono, LV_PART_MAIN | LV_STATE_PRESSED,
                                           LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_colorTimerDef);

    ui_panTempTemp2Control = lv_obj_create(ui_contTempTemp2);
    lv_obj_set_height(ui_panTempTemp2Control, 50);
    lv_obj_set_width(ui_panTempTemp2Control, lv_pct(100));
    lv_obj_set_align(ui_panTempTemp2Control, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_panTempTemp2Control, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_panTempTemp2Control, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_panTempTemp2Control, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_panTempTemp2Control, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_panTempTemp2Control, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgTempTemp2Play = lv_imagebutton_create(ui_panTempTemp2Control);
    lv_imagebutton_set_src(ui_imgTempTemp2Play, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_pause_png, NULL);
    lv_imagebutton_set_src(ui_imgTempTemp2Play, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_pause_png, NULL);
    lv_imagebutton_set_src(ui_imgTempTemp2Play, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui_img_play_png, NULL);
    lv_imagebutton_set_src(ui_imgTempTemp2Play, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_play_png, NULL);
    lv_obj_set_width(ui_imgTempTemp2Play, 48);
    lv_obj_set_height(ui_imgTempTemp2Play, 48);
    lv_obj_set_align(ui_imgTempTemp2Play, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgTempTemp2Play, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    ui_object_set_themeable_style_property(ui_imgTempTemp2Play, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_IMAGE_RECOLOR,
                                           _ui_theme_color_colorTimerDef);
    ui_object_set_themeable_style_property(ui_imgTempTemp2Play, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_IMAGE_RECOLOR_OPA,
                                           _ui_theme_alpha_colorTimerDef);

    ui_imgTempTemp2Stop = lv_imagebutton_create(ui_panTempTemp2Control);
    lv_imagebutton_set_src(ui_imgTempTemp2Stop, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_stop_png, NULL);
    lv_imagebutton_set_src(ui_imgTempTemp2Stop, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_stop_png, NULL);
    lv_obj_set_width(ui_imgTempTemp2Stop, 48);
    lv_obj_set_height(ui_imgTempTemp2Stop, 48);
    lv_obj_set_align(ui_imgTempTemp2Stop, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_imgTempTemp2Stop, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_IMAGE_RECOLOR,
                                           _ui_theme_color_colorTimerDef);
    ui_object_set_themeable_style_property(ui_imgTempTemp2Stop, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_IMAGE_RECOLOR_OPA,
                                           _ui_theme_alpha_colorTimerDef);

    ui_contTempRow2 = lv_obj_create(ui_contTempAll);
    lv_obj_remove_style_all(ui_contTempRow2);
    lv_obj_set_width(ui_contTempRow2, lv_pct(100));
    lv_obj_set_flex_grow(ui_contTempRow2, 1);
    lv_obj_set_x(ui_contTempRow2, 0);
    lv_obj_set_y(ui_contTempRow2, 32);
    lv_obj_set_align(ui_contTempRow2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_contTempRow2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_contTempRow2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contTempRow2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_contTempTemp3 = lv_obj_create(ui_contTempRow2);
    lv_obj_remove_style_all(ui_contTempTemp3);
    lv_obj_set_height(ui_contTempTemp3, lv_pct(100));
    lv_obj_set_flex_grow(ui_contTempTemp3, 1);
    lv_obj_set_align(ui_contTempTemp3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contTempTemp3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_contTempTemp3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_colorTimerDef);
    ui_object_set_themeable_style_property(ui_contTempTemp3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_colorTimerDef);
    lv_obj_set_style_border_width(ui_contTempTemp3, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_contTempTemp3, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTempTimer3Time = lv_label_create(ui_contTempTemp3);
    lv_obj_set_width(ui_lblTempTimer3Time, 100);
    lv_obj_set_height(ui_lblTempTimer3Time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblTempTimer3Time, 10);
    lv_obj_set_y(ui_lblTempTimer3Time, 10);
    lv_label_set_text(ui_lblTempTimer3Time, "--:--");
    lv_obj_set_style_text_align(ui_lblTempTimer3Time, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_lblTempTimer3Time, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_lblTempTimer3Time, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_colorTimerDef);
    ui_object_set_themeable_style_property(ui_lblTempTimer3Time, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_colorTimerDef);

    ui_lblTempTimer3Count = lv_label_create(ui_contTempTemp3);
    lv_obj_set_width(ui_lblTempTimer3Count, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTempTimer3Count, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblTempTimer3Count, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblTempTimer3Count, "--:--");
    ui_object_set_themeable_style_property(ui_lblTempTimer3Count, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_colorTimerDef);
    ui_object_set_themeable_style_property(ui_lblTempTimer3Count, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_colorTimerDef);
    lv_obj_set_style_text_font(ui_lblTempTimer3Count, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblTempTimer3Count, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblTempTimer3Count, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblTempTimer3Count, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblTempTimer3Count, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgTempTimer3Chrono = lv_image_create(ui_contTempTemp3);
    lv_image_set_src(ui_imgTempTimer3Chrono, &ui_img_timer_png);
    lv_obj_set_width(ui_imgTempTimer3Chrono, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgTempTimer3Chrono, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imgTempTimer3Chrono, -10);
    lv_obj_set_y(ui_imgTempTimer3Chrono, 10);
    lv_obj_set_align(ui_imgTempTimer3Chrono, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_imgTempTimer3Chrono, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgTempTimer3Chrono, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_imgTempTimer3Chrono, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR,
                                           _ui_theme_color_colorTimerDef);
    ui_object_set_themeable_style_property(ui_imgTempTimer3Chrono, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_colorTimerDef);

    ui_panTempTemp3Add = lv_obj_create(ui_contTempTemp3);
    lv_obj_set_height(ui_panTempTemp3Add, 50);
    lv_obj_set_width(ui_panTempTemp3Add, lv_pct(100));
    lv_obj_set_align(ui_panTempTemp3Add, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_panTempTemp3Add, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_panTempTemp3Add, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_panTempTemp3Add, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_panTempTemp3Add, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgTempTemp3AddTimer = lv_imagebutton_create(ui_panTempTemp3Add);
    lv_imagebutton_set_src(ui_imgTempTemp3AddTimer, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_hourglass_bottom_png,
                           NULL);
    lv_imagebutton_set_src(ui_imgTempTemp3AddTimer, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_hourglass_bottom_png, NULL);
    lv_obj_set_width(ui_imgTempTemp3AddTimer, 48);
    lv_obj_set_height(ui_imgTempTemp3AddTimer, 48);
    lv_obj_set_align(ui_imgTempTemp3AddTimer, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_imgTempTemp3AddTimer, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_IMAGE_RECOLOR,
                                           _ui_theme_color_colorTimerDef);
    ui_object_set_themeable_style_property(ui_imgTempTemp3AddTimer, LV_PART_MAIN | LV_STATE_PRESSED,
                                           LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_colorTimerDef);

    ui_imgTempTemp3AddChrono = lv_imagebutton_create(ui_panTempTemp3Add);
    lv_imagebutton_set_src(ui_imgTempTemp3AddChrono, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_timer_png, NULL);
    lv_imagebutton_set_src(ui_imgTempTemp3AddChrono, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_timer_png, NULL);
    lv_obj_set_width(ui_imgTempTemp3AddChrono, 48);
    lv_obj_set_height(ui_imgTempTemp3AddChrono, 48);
    lv_obj_set_align(ui_imgTempTemp3AddChrono, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_imgTempTemp3AddChrono, LV_PART_MAIN | LV_STATE_PRESSED,
                                           LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_colorTimerDef);
    ui_object_set_themeable_style_property(ui_imgTempTemp3AddChrono, LV_PART_MAIN | LV_STATE_PRESSED,
                                           LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_colorTimerDef);

    ui_panTempTemp3Control = lv_obj_create(ui_contTempTemp3);
    lv_obj_set_height(ui_panTempTemp3Control, 50);
    lv_obj_set_width(ui_panTempTemp3Control, lv_pct(100));
    lv_obj_set_align(ui_panTempTemp3Control, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_panTempTemp3Control, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_panTempTemp3Control, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_panTempTemp3Control, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_panTempTemp3Control, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_panTempTemp3Control, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgTempTemp3Play = lv_imagebutton_create(ui_panTempTemp3Control);
    lv_imagebutton_set_src(ui_imgTempTemp3Play, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_pause_png, NULL);
    lv_imagebutton_set_src(ui_imgTempTemp3Play, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_pause_png, NULL);
    lv_imagebutton_set_src(ui_imgTempTemp3Play, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui_img_play_png, NULL);
    lv_imagebutton_set_src(ui_imgTempTemp3Play, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_play_png, NULL);
    lv_obj_set_width(ui_imgTempTemp3Play, 48);
    lv_obj_set_height(ui_imgTempTemp3Play, 48);
    lv_obj_set_align(ui_imgTempTemp3Play, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgTempTemp3Play, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    ui_object_set_themeable_style_property(ui_imgTempTemp3Play, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_IMAGE_RECOLOR,
                                           _ui_theme_color_colorTimerDef);
    ui_object_set_themeable_style_property(ui_imgTempTemp3Play, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_IMAGE_RECOLOR_OPA,
                                           _ui_theme_alpha_colorTimerDef);

    ui_imgTempTemp3Stop = lv_imagebutton_create(ui_panTempTemp3Control);
    lv_imagebutton_set_src(ui_imgTempTemp3Stop, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_stop_png, NULL);
    lv_imagebutton_set_src(ui_imgTempTemp3Stop, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_stop_png, NULL);
    lv_obj_set_width(ui_imgTempTemp3Stop, 48);
    lv_obj_set_height(ui_imgTempTemp3Stop, 48);
    lv_obj_set_align(ui_imgTempTemp3Stop, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_imgTempTemp3Stop, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_IMAGE_RECOLOR,
                                           _ui_theme_color_colorTimerDef);
    ui_object_set_themeable_style_property(ui_imgTempTemp3Stop, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_IMAGE_RECOLOR_OPA,
                                           _ui_theme_alpha_colorTimerDef);

    ui_contTempTemp4 = lv_obj_create(ui_contTempRow2);
    lv_obj_remove_style_all(ui_contTempTemp4);
    lv_obj_set_height(ui_contTempTemp4, lv_pct(100));
    lv_obj_set_flex_grow(ui_contTempTemp4, 1);
    lv_obj_set_align(ui_contTempTemp4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contTempTemp4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_contTempTemp4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_colorTimerDef);
    ui_object_set_themeable_style_property(ui_contTempTemp4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_colorTimerDef);
    lv_obj_set_style_border_width(ui_contTempTemp4, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_contTempTemp4, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTempTimer4Time = lv_label_create(ui_contTempTemp4);
    lv_obj_set_width(ui_lblTempTimer4Time, 100);
    lv_obj_set_height(ui_lblTempTimer4Time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblTempTimer4Time, 10);
    lv_obj_set_y(ui_lblTempTimer4Time, 10);
    lv_label_set_text(ui_lblTempTimer4Time, "--:--");
    lv_obj_set_style_text_align(ui_lblTempTimer4Time, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_lblTempTimer4Time, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_lblTempTimer4Time, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_colorTimerDef);
    ui_object_set_themeable_style_property(ui_lblTempTimer4Time, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_colorTimerDef);

    ui_lblTempTimer4Count = lv_label_create(ui_contTempTemp4);
    lv_obj_set_width(ui_lblTempTimer4Count, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTempTimer4Count, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblTempTimer4Count, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblTempTimer4Count, "--:--");
    ui_object_set_themeable_style_property(ui_lblTempTimer4Count, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_colorTimerDef);
    ui_object_set_themeable_style_property(ui_lblTempTimer4Count, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_colorTimerDef);
    lv_obj_set_style_text_font(ui_lblTempTimer4Count, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblTempTimer4Count, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblTempTimer4Count, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblTempTimer4Count, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblTempTimer4Count, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgTempTimer4Chrono = lv_image_create(ui_contTempTemp4);
    lv_image_set_src(ui_imgTempTimer4Chrono, &ui_img_timer_png);
    lv_obj_set_width(ui_imgTempTimer4Chrono, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgTempTimer4Chrono, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imgTempTimer4Chrono, -10);
    lv_obj_set_y(ui_imgTempTimer4Chrono, 10);
    lv_obj_set_align(ui_imgTempTimer4Chrono, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_imgTempTimer4Chrono, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgTempTimer4Chrono, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_imgTempTimer4Chrono, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR,
                                           _ui_theme_color_colorTimerDef);
    ui_object_set_themeable_style_property(ui_imgTempTimer4Chrono, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_colorTimerDef);

    ui_panTempTemp4Add = lv_obj_create(ui_contTempTemp4);
    lv_obj_set_height(ui_panTempTemp4Add, 50);
    lv_obj_set_width(ui_panTempTemp4Add, lv_pct(100));
    lv_obj_set_align(ui_panTempTemp4Add, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_panTempTemp4Add, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_panTempTemp4Add, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_panTempTemp4Add, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_panTempTemp4Add, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgTempTemp4AddTimer = lv_imagebutton_create(ui_panTempTemp4Add);
    lv_imagebutton_set_src(ui_imgTempTemp4AddTimer, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_hourglass_bottom_png,
                           NULL);
    lv_imagebutton_set_src(ui_imgTempTemp4AddTimer, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_hourglass_bottom_png, NULL);
    lv_obj_set_width(ui_imgTempTemp4AddTimer, 48);
    lv_obj_set_height(ui_imgTempTemp4AddTimer, 48);
    lv_obj_set_align(ui_imgTempTemp4AddTimer, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_imgTempTemp4AddTimer, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_IMAGE_RECOLOR,
                                           _ui_theme_color_colorTimerDef);
    ui_object_set_themeable_style_property(ui_imgTempTemp4AddTimer, LV_PART_MAIN | LV_STATE_PRESSED,
                                           LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_colorTimerDef);

    ui_imgTempTemp4AddChrono = lv_imagebutton_create(ui_panTempTemp4Add);
    lv_imagebutton_set_src(ui_imgTempTemp4AddChrono, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_timer_png, NULL);
    lv_imagebutton_set_src(ui_imgTempTemp4AddChrono, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_timer_png, NULL);
    lv_obj_set_width(ui_imgTempTemp4AddChrono, 48);
    lv_obj_set_height(ui_imgTempTemp4AddChrono, 48);
    lv_obj_set_align(ui_imgTempTemp4AddChrono, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_imgTempTemp4AddChrono, LV_PART_MAIN | LV_STATE_PRESSED,
                                           LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_colorTimerDef);
    ui_object_set_themeable_style_property(ui_imgTempTemp4AddChrono, LV_PART_MAIN | LV_STATE_PRESSED,
                                           LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_colorTimerDef);

    ui_panTempTemp4Control = lv_obj_create(ui_contTempTemp4);
    lv_obj_set_height(ui_panTempTemp4Control, 50);
    lv_obj_set_width(ui_panTempTemp4Control, lv_pct(100));
    lv_obj_set_align(ui_panTempTemp4Control, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_panTempTemp4Control, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_panTempTemp4Control, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_panTempTemp4Control, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_panTempTemp4Control, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_panTempTemp4Control, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgTempTemp4Play = lv_imagebutton_create(ui_panTempTemp4Control);
    lv_imagebutton_set_src(ui_imgTempTemp4Play, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_pause_png, NULL);
    lv_imagebutton_set_src(ui_imgTempTemp4Play, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_pause_png, NULL);
    lv_imagebutton_set_src(ui_imgTempTemp4Play, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui_img_play_png, NULL);
    lv_imagebutton_set_src(ui_imgTempTemp4Play, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_play_png, NULL);
    lv_obj_set_width(ui_imgTempTemp4Play, 48);
    lv_obj_set_height(ui_imgTempTemp4Play, 48);
    lv_obj_set_align(ui_imgTempTemp4Play, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgTempTemp4Play, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    ui_object_set_themeable_style_property(ui_imgTempTemp4Play, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_IMAGE_RECOLOR,
                                           _ui_theme_color_colorTimerDef);
    ui_object_set_themeable_style_property(ui_imgTempTemp4Play, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_IMAGE_RECOLOR_OPA,
                                           _ui_theme_alpha_colorTimerDef);

    ui_imgTempTemp4Stop = lv_imagebutton_create(ui_panTempTemp4Control);
    lv_imagebutton_set_src(ui_imgTempTemp4Stop, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_stop_png, NULL);
    lv_imagebutton_set_src(ui_imgTempTemp4Stop, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_stop_png, NULL);
    lv_obj_set_width(ui_imgTempTemp4Stop, 48);
    lv_obj_set_height(ui_imgTempTemp4Stop, 48);
    lv_obj_set_align(ui_imgTempTemp4Stop, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_imgTempTemp4Stop, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_IMAGE_RECOLOR,
                                           _ui_theme_color_colorTimerDef);
    ui_object_set_themeable_style_property(ui_imgTempTemp4Stop, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_IMAGE_RECOLOR_OPA,
                                           _ui_theme_alpha_colorTimerDef);

    ui_panTempSound = lv_obj_create(ui_scrTimers);
    lv_obj_set_width(ui_panTempSound, 400);
    lv_obj_set_height(ui_panTempSound, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_panTempSound, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_panTempSound, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_panTempSound, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_panTempSound, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_panTempSound, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_panTempSound, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_colorShadow);
    ui_object_set_themeable_style_property(ui_panTempSound, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_colorShadow);
    ui_object_set_themeable_style_property(ui_panTempSound, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_COLOR,
                                           _ui_theme_color_colorShadow);
    ui_object_set_themeable_style_property(ui_panTempSound, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_OPA,
                                           _ui_theme_alpha_colorShadow);
    lv_obj_set_style_shadow_width(ui_panTempSound, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_panTempSound, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_panTempSound, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_panTempSound, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_conTempSoundHigh = lv_obj_create(ui_panTempSound);
    lv_obj_remove_style_all(ui_conTempSoundHigh);
    lv_obj_set_height(ui_conTempSoundHigh, 200);
    lv_obj_set_width(ui_conTempSoundHigh, lv_pct(100));
    lv_obj_set_align(ui_conTempSoundHigh, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_conTempSoundHigh, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_conTempSoundHigh, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_conTempSoundHigh, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_contTempSoundTheme = lv_obj_create(ui_conTempSoundHigh);
    lv_obj_remove_style_all(ui_contTempSoundTheme);
    lv_obj_set_height(ui_contTempSoundTheme, lv_pct(100));
    lv_obj_set_flex_grow(ui_contTempSoundTheme, 1);
    lv_obj_set_align(ui_contTempSoundTheme, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_contTempSoundTheme, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_contTempSoundTheme, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contTempSoundTheme, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblTempSoundTheme = lv_label_create(ui_contTempSoundTheme);
    lv_obj_set_width(ui_lblTempSoundTheme, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTempSoundTheme, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblTempSoundTheme, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblTempSoundTheme, "Sonido");

    ui_rollSoundTheme = lv_roller_create(ui_contTempSoundTheme);
    lv_roller_set_options(ui_rollSoundTheme, "alarm\nbeepbeep\nbip\nboat\ncukoo\nmorse", LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(ui_rollSoundTheme, 1, LV_ANIM_OFF);
    lv_obj_set_width(ui_rollSoundTheme, 150);
    lv_obj_set_height(ui_rollSoundTheme, 150);
    lv_obj_set_align(ui_rollSoundTheme, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_rollSoundTheme, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_colorTimerDef);
    ui_object_set_themeable_style_property(ui_rollSoundTheme, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_colorTimerDef);

    ui_contTempSoundVolume = lv_obj_create(ui_conTempSoundHigh);
    lv_obj_remove_style_all(ui_contTempSoundVolume);
    lv_obj_set_height(ui_contTempSoundVolume, lv_pct(100));
    lv_obj_set_flex_grow(ui_contTempSoundVolume, 1);
    lv_obj_set_align(ui_contTempSoundVolume, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_contTempSoundVolume, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_contTempSoundVolume, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contTempSoundVolume, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblTempSoundVolume = lv_label_create(ui_contTempSoundVolume);
    lv_obj_set_width(ui_lblTempSoundVolume, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTempSoundVolume, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblTempSoundVolume, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblTempSoundVolume, "Volumen\n0%");
    lv_obj_set_style_text_align(ui_lblTempSoundVolume, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sldTempSoundVolume = lv_slider_create(ui_contTempSoundVolume);
    lv_slider_set_range(ui_sldTempSoundVolume, 0, 3);
    lv_slider_set_value(ui_sldTempSoundVolume, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_sldTempSoundVolume) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_sldTempSoundVolume, 0,
                                                                                                       LV_ANIM_OFF);
    lv_obj_set_height(ui_sldTempSoundVolume, 15);
    lv_obj_set_width(ui_sldTempSoundVolume, lv_pct(80));
    lv_obj_set_align(ui_sldTempSoundVolume, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_sldTempSoundVolume, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_sldTempSoundVolume,
                                                                                                         lv_obj_get_style_pad_right(ui_sldTempSoundVolume, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_conTempSoundBtn = lv_obj_create(ui_panTempSound);
    lv_obj_remove_style_all(ui_conTempSoundBtn);
    lv_obj_set_width(ui_conTempSoundBtn, lv_pct(100));
    lv_obj_set_height(ui_conTempSoundBtn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_conTempSoundBtn, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_conTempSoundBtn, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_conTempSoundBtn, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_conTempSoundBtn, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnTempSoundOk = lv_button_create(ui_conTempSoundBtn);
    lv_obj_set_width(ui_btnTempSoundOk, 100);
    lv_obj_set_height(ui_btnTempSoundOk, 40);
    lv_obj_set_align(ui_btnTempSoundOk, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnTempSoundOk, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnTempSoundOk, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblTempSoundOk = lv_label_create(ui_btnTempSoundOk);
    lv_obj_set_width(ui_lblTempSoundOk, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTempSoundOk, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblTempSoundOk, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblTempSoundOk, "Done");

    lv_obj_add_event_cb(ui_imgTempHome, ui_event_imgTempHome, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_imgTempHeaderVol, ui_event_imgTempHeaderVol, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_imgTempTemp1AddTimer, ui_event_imgTempTemp1AddTimer, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_imgTempTemp1AddChrono, ui_event_imgTempTemp1AddChrono, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_imgTempTemp1Play, ui_event_imgTempTemp1Play, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_imgTempTemp1Stop, ui_event_imgTempTemp1Stop, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_imgTempTemp2AddTimer, ui_event_imgTempTemp2AddTimer, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_imgTempTemp2AddChrono, ui_event_imgTempTemp2AddChrono, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_imgTempTemp2Play, ui_event_imgTempTemp2Play, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_imgTempTemp2Stop, ui_event_imgTempTemp2Stop, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_imgTempTemp3AddTimer, ui_event_imgTempTemp3AddTimer, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_imgTempTemp3AddChrono, ui_event_imgTempTemp3AddChrono, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_imgTempTemp3Play, ui_event_imgTempTemp3Play, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_imgTempTemp3Stop, ui_event_imgTempTemp3Stop, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_imgTempTemp4AddTimer, ui_event_imgTempTemp4AddTimer, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_imgTempTemp4AddChrono, ui_event_imgTempTemp4AddChrono, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_imgTempTemp4Play, ui_event_imgTempTemp4Play, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_imgTempTemp4Stop, ui_event_imgTempTemp4Stop, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_rollSoundTheme, ui_event_rollSoundTheme, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_sldTempSoundVolume, ui_event_sldTempSoundVolume, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnTempSoundOk, ui_event_btnTempSoundOk, LV_EVENT_ALL, NULL);

}

void ui_scrTimers_screen_destroy(void)
{
    if(ui_scrTimers) lv_obj_del(ui_scrTimers);

    // NULL screen variables
    ui_scrTimers = NULL;
    ui_panTempHeader = NULL;
    ui_imgTempHome = NULL;
    ui_lblTempHeader = NULL;
    ui_imgTempHeaderVol = NULL;
    ui_contTempAll = NULL;
    ui_contTempRow1 = NULL;
    ui_contTempTemp1 = NULL;
    ui_lblTempTimer1Time = NULL;
    ui_lblTempTimer1Count = NULL;
    ui_imgTempTimer1Chrono = NULL;
    ui_panTempTemp1Add = NULL;
    ui_imgTempTemp1AddTimer = NULL;
    ui_imgTempTemp1AddChrono = NULL;
    ui_panTempTemp1Control = NULL;
    ui_imgTempTemp1Play = NULL;
    ui_imgTempTemp1Stop = NULL;
    ui_contTempTemp2 = NULL;
    ui_lblTempTimer2Time = NULL;
    ui_lblTempTimer2Count = NULL;
    ui_imgTempTimer2Chrono = NULL;
    ui_panTempTemp2Add = NULL;
    ui_imgTempTemp2AddTimer = NULL;
    ui_imgTempTemp2AddChrono = NULL;
    ui_panTempTemp2Control = NULL;
    ui_imgTempTemp2Play = NULL;
    ui_imgTempTemp2Stop = NULL;
    ui_contTempRow2 = NULL;
    ui_contTempTemp3 = NULL;
    ui_lblTempTimer3Time = NULL;
    ui_lblTempTimer3Count = NULL;
    ui_imgTempTimer3Chrono = NULL;
    ui_panTempTemp3Add = NULL;
    ui_imgTempTemp3AddTimer = NULL;
    ui_imgTempTemp3AddChrono = NULL;
    ui_panTempTemp3Control = NULL;
    ui_imgTempTemp3Play = NULL;
    ui_imgTempTemp3Stop = NULL;
    ui_contTempTemp4 = NULL;
    ui_lblTempTimer4Time = NULL;
    ui_lblTempTimer4Count = NULL;
    ui_imgTempTimer4Chrono = NULL;
    ui_panTempTemp4Add = NULL;
    ui_imgTempTemp4AddTimer = NULL;
    ui_imgTempTemp4AddChrono = NULL;
    ui_panTempTemp4Control = NULL;
    ui_imgTempTemp4Play = NULL;
    ui_imgTempTemp4Stop = NULL;
    ui_panTempSound = NULL;
    ui_conTempSoundHigh = NULL;
    ui_contTempSoundTheme = NULL;
    ui_lblTempSoundTheme = NULL;
    ui_rollSoundTheme = NULL;
    ui_contTempSoundVolume = NULL;
    ui_lblTempSoundVolume = NULL;
    ui_sldTempSoundVolume = NULL;
    ui_conTempSoundBtn = NULL;
    ui_btnTempSoundOk = NULL;
    ui_lblTempSoundOk = NULL;

}
