// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: esp32-kitchen-timer

#include "ui.h"

lv_obj_t * ui_scrMain = NULL;
lv_obj_t * ui_panMainHeader = NULL;
lv_obj_t * ui_imgMainHome = NULL;
lv_obj_t * ui_imgMainCalendar = NULL;
lv_obj_t * ui_imgMainTimer = NULL;
lv_obj_t * ui_contMain01 = NULL;
lv_obj_t * ui_contMainWeather01 = NULL;
lv_obj_t * ui_imgMainSeeing = NULL;
lv_obj_t * ui_imgMainForecast = NULL;
lv_obj_t * ui_lblMainForecast = NULL;
lv_obj_t * ui_lblMainTime = NULL;
lv_obj_t * ui_lblMainDate = NULL;
lv_obj_t * ui_contMainWeather02 = NULL;
lv_obj_t * ui_contMainTemp = NULL;
lv_obj_t * ui_imgMainTemp = NULL;
lv_obj_t * ui_lblMainTemp = NULL;
lv_obj_t * ui_contMainHumidity = NULL;
lv_obj_t * ui_imgMainHumidity = NULL;
lv_obj_t * ui_lblMainHumidity = NULL;
lv_obj_t * ui_contMainWind = NULL;
lv_obj_t * ui_imgMainWind = NULL;
lv_obj_t * ui_lblMainWind = NULL;
lv_obj_t * ui_contMainSun = NULL;
lv_obj_t * ui_contMainSunrise = NULL;
lv_obj_t * ui_imgMainSunrise = NULL;
lv_obj_t * ui_lblMainSunrise = NULL;
lv_obj_t * ui_contMainSunset = NULL;
lv_obj_t * ui_imgMainSunset = NULL;
lv_obj_t * ui_lblMainSunset = NULL;
lv_obj_t * ui_calMain = NULL;
// event funtions
void ui_event_imgMainHome(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrHome, LV_SCR_LOAD_ANIM_NONE, 250, 0, &ui_scrHome_screen_init);
    }
}

void ui_event_imgMainCalendar(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_calMain, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_imgMainTimer(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrTimers, LV_SCR_LOAD_ANIM_NONE, 250, 0, &ui_scrTimers_screen_init);
    }
}

// build funtions

void ui_scrMain_screen_init(void)
{
    ui_scrMain = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_scrMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_scrMain, &ui_img_background_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_scrMain, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panMainHeader = lv_obj_create(ui_scrMain);
    lv_obj_set_height(ui_panMainHeader, 50);
    lv_obj_set_width(ui_panMainHeader, lv_pct(100));
    lv_obj_set_flex_flow(ui_panMainHeader, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_panMainHeader, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_panMainHeader, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_panMainHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panMainHeader, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panMainHeader, 64, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgMainHome = lv_imagebutton_create(ui_panMainHeader);
    lv_imagebutton_set_src(ui_imgMainHome, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_home_big_png, NULL);
    lv_imagebutton_set_src(ui_imgMainHome, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_home_big_png, NULL);
    lv_obj_set_width(ui_imgMainHome, 48);
    lv_obj_set_height(ui_imgMainHome, 48);
    lv_obj_set_align(ui_imgMainHome, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_imgMainHome, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_IMAGE_RECOLOR,
                                           _ui_theme_color_colorTimerDef);
    ui_object_set_themeable_style_property(ui_imgMainHome, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_IMAGE_RECOLOR_OPA,
                                           _ui_theme_alpha_colorTimerDef);

    ui_imgMainCalendar = lv_imagebutton_create(ui_panMainHeader);
    lv_imagebutton_set_src(ui_imgMainCalendar, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_calendar_png, NULL);
    lv_imagebutton_set_src(ui_imgMainCalendar, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_calendar_png, NULL);
    lv_obj_set_width(ui_imgMainCalendar, 48);
    lv_obj_set_height(ui_imgMainCalendar, 48);
    lv_obj_set_align(ui_imgMainCalendar, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_imgMainCalendar, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_IMAGE_RECOLOR,
                                           _ui_theme_color_colorTimerDef);
    ui_object_set_themeable_style_property(ui_imgMainCalendar, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_IMAGE_RECOLOR_OPA,
                                           _ui_theme_alpha_colorTimerDef);

    ui_imgMainTimer = lv_imagebutton_create(ui_panMainHeader);
    lv_imagebutton_set_src(ui_imgMainTimer, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_timer_png, NULL);
    lv_imagebutton_set_src(ui_imgMainTimer, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_timer_png, NULL);
    lv_obj_set_width(ui_imgMainTimer, 48);
    lv_obj_set_height(ui_imgMainTimer, 48);
    lv_obj_set_align(ui_imgMainTimer, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_imgMainTimer, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_IMAGE_RECOLOR,
                                           _ui_theme_color_colorTimerDef);
    ui_object_set_themeable_style_property(ui_imgMainTimer, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_IMAGE_RECOLOR_OPA,
                                           _ui_theme_alpha_colorTimerDef);

    ui_contMain01 = lv_obj_create(ui_scrMain);
    lv_obj_remove_style_all(ui_contMain01);
    lv_obj_set_height(ui_contMain01, 420);
    lv_obj_set_width(ui_contMain01, lv_pct(95));
    lv_obj_set_y(ui_contMain01, 0);
    lv_obj_set_x(ui_contMain01, lv_pct(5));
    lv_obj_set_align(ui_contMain01, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_set_flex_flow(ui_contMain01, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_contMain01, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_contMain01, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgMainSeeing = lv_image_create(ui_contMain01);
    lv_image_set_src(ui_imgMainSeeing, LV_SYMBOL_DUMMY "No seeing data");
    lv_obj_set_width(ui_imgMainSeeing, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgMainSeeing, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgMainSeeing, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_imgMainSeeing, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgMainSeeing, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_contMainWeather01 = lv_obj_create(ui_contMain01);
    lv_obj_remove_style_all(ui_contMainWeather01);
    lv_obj_set_width(ui_contMainWeather01, lv_pct(100));
    lv_obj_set_height(ui_contMainWeather01, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_contMainWeather01, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_contMainWeather01, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_contMainWeather01, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contMainWeather01, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgMainForecast = lv_image_create(ui_contMainWeather01);
    lv_image_set_src(ui_imgMainForecast, &ui_img_sun_png);
    lv_obj_set_width(ui_imgMainForecast, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgMainForecast, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgMainForecast, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgMainForecast, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgMainForecast, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblMainForecast = lv_label_create(ui_contMainWeather01);
    lv_obj_set_width(ui_lblMainForecast, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblMainForecast, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblMainForecast, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblMainForecast, "muy nuboso");
    lv_obj_set_style_pad_left(ui_lblMainForecast, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblMainForecast, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblMainForecast, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblMainForecast, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblMainTime = lv_label_create(ui_contMain01);
    lv_obj_set_width(ui_lblMainTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblMainTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblMainTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblMainTime, "00:00");
    lv_obj_set_style_text_font(ui_lblMainTime, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblMainDate = lv_label_create(ui_contMain01);
    lv_obj_set_width(ui_lblMainDate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblMainDate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblMainDate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblMainDate, "Jueves, 18 de diciembre de 2025");

    ui_contMainWeather02 = lv_obj_create(ui_contMain01);
    lv_obj_remove_style_all(ui_contMainWeather02);
    lv_obj_set_width(ui_contMainWeather02, lv_pct(100));
    lv_obj_set_height(ui_contMainWeather02, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_contMainWeather02, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_contMainWeather02, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_contMainWeather02, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contMainWeather02, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_contMainTemp = lv_obj_create(ui_contMainWeather02);
    lv_obj_remove_style_all(ui_contMainTemp);
    lv_obj_set_width(ui_contMainTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_contMainTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_contMainTemp, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_contMainTemp, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_contMainTemp, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contMainTemp, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgMainTemp = lv_image_create(ui_contMainTemp);
    lv_image_set_src(ui_imgMainTemp, &ui_img_thermo_png);
    lv_obj_set_width(ui_imgMainTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgMainTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgMainTemp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgMainTemp, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgMainTemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblMainTemp = lv_label_create(ui_contMainTemp);
    lv_obj_set_width(ui_lblMainTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblMainTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblMainTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblMainTemp, "21 C");

    ui_contMainHumidity = lv_obj_create(ui_contMainWeather02);
    lv_obj_remove_style_all(ui_contMainHumidity);
    lv_obj_set_width(ui_contMainHumidity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_contMainHumidity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_contMainHumidity, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_contMainHumidity, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_contMainHumidity, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contMainHumidity, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgMainHumidity = lv_image_create(ui_contMainHumidity);
    lv_image_set_src(ui_imgMainHumidity, &ui_img_drop_png);
    lv_obj_set_width(ui_imgMainHumidity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgMainHumidity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgMainHumidity, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgMainHumidity, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgMainHumidity, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblMainHumidity = lv_label_create(ui_contMainHumidity);
    lv_obj_set_width(ui_lblMainHumidity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblMainHumidity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblMainHumidity, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblMainHumidity, "50%");

    ui_contMainWind = lv_obj_create(ui_contMainWeather02);
    lv_obj_remove_style_all(ui_contMainWind);
    lv_obj_set_width(ui_contMainWind, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_contMainWind, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_contMainWind, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_contMainWind, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_contMainWind, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contMainWind, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgMainWind = lv_image_create(ui_contMainWind);
    lv_image_set_src(ui_imgMainWind, &ui_img_wind_png);
    lv_obj_set_width(ui_imgMainWind, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgMainWind, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgMainWind, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgMainWind, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgMainWind, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblMainWind = lv_label_create(ui_contMainWind);
    lv_obj_set_width(ui_lblMainWind, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblMainWind, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblMainWind, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblMainWind, "10");

    ui_contMainSun = lv_obj_create(ui_contMain01);
    lv_obj_remove_style_all(ui_contMainSun);
    lv_obj_set_width(ui_contMainSun, lv_pct(100));
    lv_obj_set_height(ui_contMainSun, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_contMainSun, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_contMainSun, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_contMainSun, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contMainSun, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_contMainSunrise = lv_obj_create(ui_contMainSun);
    lv_obj_remove_style_all(ui_contMainSunrise);
    lv_obj_set_width(ui_contMainSunrise, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_contMainSunrise, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_contMainSunrise, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_contMainSunrise, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_contMainSunrise, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contMainSunrise, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgMainSunrise = lv_image_create(ui_contMainSunrise);
    lv_image_set_src(ui_imgMainSunrise, &ui_img_sunrise_png);
    lv_obj_set_width(ui_imgMainSunrise, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgMainSunrise, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgMainSunrise, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgMainSunrise, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgMainSunrise, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblMainSunrise = lv_label_create(ui_contMainSunrise);
    lv_obj_set_width(ui_lblMainSunrise, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblMainSunrise, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblMainSunrise, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblMainSunrise, "08:00");

    ui_contMainSunset = lv_obj_create(ui_contMainSun);
    lv_obj_remove_style_all(ui_contMainSunset);
    lv_obj_set_width(ui_contMainSunset, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_contMainSunset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_contMainSunset, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_contMainSunset, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_contMainSunset, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contMainSunset, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgMainSunset = lv_image_create(ui_contMainSunset);
    lv_image_set_src(ui_imgMainSunset, &ui_img_moon_png);
    lv_obj_set_width(ui_imgMainSunset, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgMainSunset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgMainSunset, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgMainSunset, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgMainSunset, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblMainSunset = lv_label_create(ui_contMainSunset);
    lv_obj_set_width(ui_lblMainSunset, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblMainSunset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblMainSunset, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblMainSunset, "23:00");

    ui_calMain = lv_calendar_create(ui_scrMain);
    lv_calendar_set_today_date(ui_calMain, 2026, 1, 1);
    lv_calendar_set_showed_date(ui_calMain, 2026, 1);
    lv_obj_t * ui_calMain_header = lv_calendar_header_arrow_create(ui_calMain);
    lv_obj_set_height(ui_calMain, 380);
    lv_obj_set_width(ui_calMain, lv_pct(100));
    lv_obj_set_align(ui_calMain, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_calMain, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_calMain, LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags

    lv_obj_add_event_cb(ui_imgMainHome, ui_event_imgMainHome, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_imgMainCalendar, ui_event_imgMainCalendar, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_imgMainTimer, ui_event_imgMainTimer, LV_EVENT_ALL, NULL);

}

void ui_scrMain_screen_destroy(void)
{
    if(ui_scrMain) lv_obj_del(ui_scrMain);

    // NULL screen variables
    ui_scrMain = NULL;
    ui_panMainHeader = NULL;
    ui_imgMainHome = NULL;
    ui_imgMainCalendar = NULL;
    ui_imgMainTimer = NULL;
    ui_contMain01 = NULL;
    ui_contMainWeather01 = NULL;
    ui_imgMainSeeing = NULL;
    ui_imgMainForecast = NULL;
    ui_lblMainForecast = NULL;
    ui_lblMainTime = NULL;
    ui_lblMainDate = NULL;
    ui_contMainWeather02 = NULL;
    ui_contMainTemp = NULL;
    ui_imgMainTemp = NULL;
    ui_lblMainTemp = NULL;
    ui_contMainHumidity = NULL;
    ui_imgMainHumidity = NULL;
    ui_lblMainHumidity = NULL;
    ui_contMainWind = NULL;
    ui_imgMainWind = NULL;
    ui_lblMainWind = NULL;
    ui_contMainSun = NULL;
    ui_contMainSunrise = NULL;
    ui_imgMainSunrise = NULL;
    ui_lblMainSunrise = NULL;
    ui_contMainSunset = NULL;
    ui_imgMainSunset = NULL;
    ui_lblMainSunset = NULL;
    ui_calMain = NULL;

}
