// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: esp32-kitchen-timer

#include "ui.h"

lv_obj_t * uic_scrTimer;
lv_obj_t * ui_scrNewTimer = NULL;
lv_obj_t * ui_lblTempNewHeader = NULL;
lv_obj_t * ui_contTempNewTimer = NULL;
lv_obj_t * ui_rollTempNewMinDec = NULL;
lv_obj_t * ui_rollTempNewMin = NULL;
lv_obj_t * ui_lblTempNewTimer = NULL;
lv_obj_t * ui_contTempNewTimer2 = NULL;
lv_obj_t * ui_btnTempNewTimer03 = NULL;
lv_obj_t * ui_lblTempNewTimer03 = NULL;
lv_obj_t * ui_btnTempNewTimer06 = NULL;
lv_obj_t * ui_lblTempNewTimer06 = NULL;
lv_obj_t * ui_btnTempNewTimer07 = NULL;
lv_obj_t * ui_lblTempNewTimer07 = NULL;
lv_obj_t * ui_btnTempNewTimer08 = NULL;
lv_obj_t * ui_lblTempNewTimer08 = NULL;
lv_obj_t * ui_contTempNewTimer03 = NULL;
lv_obj_t * ui_btnTempNewOK = NULL;
lv_obj_t * ui_lblTempNewOK = NULL;
lv_obj_t * ui_btnTempNewCancel = NULL;
lv_obj_t * ui_lblTempNewCancel = NULL;
// event funtions
void ui_event_btnTempNewTimer03(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_roller_set_property(ui_rollTempNewMinDec, _UI_ROLLER_PROPERTY_SELECTED_WITH_ANIM, 1);
        _ui_roller_set_property(ui_rollTempNewMin, _UI_ROLLER_PROPERTY_SELECTED_WITH_ANIM, 5);
    }
}

void ui_event_btnTempNewTimer06(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_roller_set_property(ui_rollTempNewMinDec, _UI_ROLLER_PROPERTY_SELECTED_WITH_ANIM, 3);
        _ui_roller_set_property(ui_rollTempNewMin, _UI_ROLLER_PROPERTY_SELECTED_WITH_ANIM, 0);
    }
}

void ui_event_btnTempNewTimer07(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_roller_set_property(ui_rollTempNewMinDec, _UI_ROLLER_PROPERTY_SELECTED_WITH_ANIM, 4);
        _ui_roller_set_property(ui_rollTempNewMin, _UI_ROLLER_PROPERTY_SELECTED_WITH_ANIM, 5);
    }
}

void ui_event_btnTempNewTimer08(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_roller_set_property(ui_rollTempNewMinDec, _UI_ROLLER_PROPERTY_SELECTED_WITH_ANIM, 6);
        _ui_roller_set_property(ui_rollTempNewMin, _UI_ROLLER_PROPERTY_SELECTED_WITH_ANIM, 0);
    }
}

void ui_event_btnTempNewOK(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        btnTempNewOKClick(e);
    }
}

void ui_event_btnTempNewCancel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrTimers, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_scrTimers_screen_init);
    }
}

// build funtions

void ui_scrNewTimer_screen_init(void)
{
    ui_scrNewTimer = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_scrNewTimer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_scrNewTimer, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTempNewHeader = lv_label_create(ui_scrNewTimer);
    lv_obj_set_height(ui_lblTempNewHeader, 40);
    lv_obj_set_width(ui_lblTempNewHeader, lv_pct(100));
    lv_label_set_text(ui_lblTempNewHeader, "TEMPORIZADOR 1");
    lv_obj_set_style_text_align(ui_lblTempNewHeader, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblTempNewHeader, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblTempNewHeader, 64, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblTempNewHeader, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblTempNewHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblTempNewHeader, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_lblTempNewHeader, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblTempNewHeader, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblTempNewHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblTempNewHeader, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblTempNewHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contTempNewTimer = lv_obj_create(ui_scrNewTimer);
    lv_obj_remove_style_all(ui_contTempNewTimer);
    lv_obj_set_height(ui_contTempNewTimer, 200);
    lv_obj_set_width(ui_contTempNewTimer, lv_pct(100));
    lv_obj_set_x(ui_contTempNewTimer, 0);
    lv_obj_set_y(ui_contTempNewTimer, 50);
    lv_obj_set_flex_flow(ui_contTempNewTimer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_contTempNewTimer, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contTempNewTimer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_rollTempNewMinDec = lv_roller_create(ui_contTempNewTimer);
    lv_roller_set_options(ui_rollTempNewMinDec, "0\n1\n2\n3\n4\n5\n6\n7\n8\n9", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_rollTempNewMinDec, lv_pct(30));
    lv_obj_set_height(ui_rollTempNewMinDec, lv_pct(90));
    lv_obj_set_align(ui_rollTempNewMinDec, LV_ALIGN_CENTER);
    lv_obj_set_scroll_dir(ui_rollTempNewMinDec, LV_DIR_VER);
    lv_obj_set_style_text_font(ui_rollTempNewMinDec, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rollTempNewMinDec, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rollTempNewMinDec, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_rollTempNewMinDec, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_COLOR,
                                           _ui_theme_color_colorShadow);
    ui_object_set_themeable_style_property(ui_rollTempNewMinDec, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_OPA,
                                           _ui_theme_alpha_colorShadow);
    lv_obj_set_style_shadow_width(ui_rollTempNewMinDec, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_rollTempNewMinDec, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_rollTempNewMinDec, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_rollTempNewMinDec, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rollTempNewMin = lv_roller_create(ui_contTempNewTimer);
    lv_roller_set_options(ui_rollTempNewMin, "0\n1\n2\n3\n4\n5\n6\n7\n8\n9", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_rollTempNewMin, lv_pct(30));
    lv_obj_set_height(ui_rollTempNewMin, lv_pct(90));
    lv_obj_set_align(ui_rollTempNewMin, LV_ALIGN_CENTER);
    lv_obj_set_scroll_dir(ui_rollTempNewMin, LV_DIR_VER);
    lv_obj_set_style_text_font(ui_rollTempNewMin, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rollTempNewMin, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rollTempNewMin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_rollTempNewMin, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_COLOR,
                                           _ui_theme_color_colorShadow);
    ui_object_set_themeable_style_property(ui_rollTempNewMin, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_OPA,
                                           _ui_theme_alpha_colorShadow);
    lv_obj_set_style_shadow_width(ui_rollTempNewMin, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_rollTempNewMin, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_rollTempNewMin, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_rollTempNewMin, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTempNewTimer = lv_label_create(ui_contTempNewTimer);
    lv_obj_set_width(ui_lblTempNewTimer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTempNewTimer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblTempNewTimer, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblTempNewTimer, "min");
    lv_obj_set_style_text_font(ui_lblTempNewTimer, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contTempNewTimer2 = lv_obj_create(ui_scrNewTimer);
    lv_obj_remove_style_all(ui_contTempNewTimer2);
    lv_obj_set_height(ui_contTempNewTimer2, 100);
    lv_obj_set_width(ui_contTempNewTimer2, lv_pct(100));
    lv_obj_set_x(ui_contTempNewTimer2, 0);
    lv_obj_set_y(ui_contTempNewTimer2, 270);
    lv_obj_set_flex_flow(ui_contTempNewTimer2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_contTempNewTimer2, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contTempNewTimer2, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_scroll_dir(ui_contTempNewTimer2, LV_DIR_HOR);
    lv_obj_set_style_pad_row(ui_contTempNewTimer2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_contTempNewTimer2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnTempNewTimer03 = lv_button_create(ui_contTempNewTimer2);
    lv_obj_set_width(ui_btnTempNewTimer03, 100);
    lv_obj_set_height(ui_btnTempNewTimer03, lv_pct(90));
    lv_obj_set_align(ui_btnTempNewTimer03, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnTempNewTimer03, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnTempNewTimer03, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblTempNewTimer03 = lv_label_create(ui_btnTempNewTimer03);
    lv_obj_set_width(ui_lblTempNewTimer03, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTempNewTimer03, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblTempNewTimer03, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblTempNewTimer03, "15m");

    ui_btnTempNewTimer06 = lv_button_create(ui_contTempNewTimer2);
    lv_obj_set_width(ui_btnTempNewTimer06, 100);
    lv_obj_set_height(ui_btnTempNewTimer06, lv_pct(90));
    lv_obj_set_align(ui_btnTempNewTimer06, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnTempNewTimer06, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnTempNewTimer06, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblTempNewTimer06 = lv_label_create(ui_btnTempNewTimer06);
    lv_obj_set_width(ui_lblTempNewTimer06, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTempNewTimer06, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblTempNewTimer06, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblTempNewTimer06, "30m");

    ui_btnTempNewTimer07 = lv_button_create(ui_contTempNewTimer2);
    lv_obj_set_width(ui_btnTempNewTimer07, 100);
    lv_obj_set_height(ui_btnTempNewTimer07, lv_pct(90));
    lv_obj_set_align(ui_btnTempNewTimer07, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnTempNewTimer07, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnTempNewTimer07, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblTempNewTimer07 = lv_label_create(ui_btnTempNewTimer07);
    lv_obj_set_width(ui_lblTempNewTimer07, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTempNewTimer07, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblTempNewTimer07, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblTempNewTimer07, "45m");

    ui_btnTempNewTimer08 = lv_button_create(ui_contTempNewTimer2);
    lv_obj_set_width(ui_btnTempNewTimer08, 100);
    lv_obj_set_height(ui_btnTempNewTimer08, lv_pct(90));
    lv_obj_set_align(ui_btnTempNewTimer08, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnTempNewTimer08, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnTempNewTimer08, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblTempNewTimer08 = lv_label_create(ui_btnTempNewTimer08);
    lv_obj_set_width(ui_lblTempNewTimer08, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTempNewTimer08, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblTempNewTimer08, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblTempNewTimer08, "60m");

    ui_contTempNewTimer03 = lv_obj_create(ui_scrNewTimer);
    lv_obj_remove_style_all(ui_contTempNewTimer03);
    lv_obj_set_height(ui_contTempNewTimer03, 100);
    lv_obj_set_width(ui_contTempNewTimer03, lv_pct(100));
    lv_obj_set_align(ui_contTempNewTimer03, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_set_flex_flow(ui_contTempNewTimer03, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_contTempNewTimer03, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contTempNewTimer03, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_contTempNewTimer03, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_contTempNewTimer03, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnTempNewOK = lv_button_create(ui_contTempNewTimer03);
    lv_obj_set_height(ui_btnTempNewOK, lv_pct(70));
    lv_obj_set_flex_grow(ui_btnTempNewOK, 1);
    lv_obj_set_align(ui_btnTempNewOK, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnTempNewOK, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnTempNewOK, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnTempNewOK, lv_color_hex(0x539A2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnTempNewOK, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTempNewOK = lv_label_create(ui_btnTempNewOK);
    lv_obj_set_width(ui_lblTempNewOK, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTempNewOK, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblTempNewOK, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblTempNewOK, "OK");

    ui_btnTempNewCancel = lv_button_create(ui_contTempNewTimer03);
    lv_obj_set_height(ui_btnTempNewCancel, lv_pct(70));
    lv_obj_set_flex_grow(ui_btnTempNewCancel, 1);
    lv_obj_set_align(ui_btnTempNewCancel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnTempNewCancel, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnTempNewCancel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnTempNewCancel, lv_color_hex(0x992E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnTempNewCancel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTempNewCancel = lv_label_create(ui_btnTempNewCancel);
    lv_obj_set_width(ui_lblTempNewCancel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTempNewCancel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblTempNewCancel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblTempNewCancel, "Cancel");

    lv_obj_add_event_cb(ui_btnTempNewTimer03, ui_event_btnTempNewTimer03, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnTempNewTimer06, ui_event_btnTempNewTimer06, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnTempNewTimer07, ui_event_btnTempNewTimer07, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnTempNewTimer08, ui_event_btnTempNewTimer08, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnTempNewOK, ui_event_btnTempNewOK, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnTempNewCancel, ui_event_btnTempNewCancel, LV_EVENT_ALL, NULL);
    uic_scrTimer = ui_scrNewTimer;

}

void ui_scrNewTimer_screen_destroy(void)
{
    if(ui_scrNewTimer) lv_obj_del(ui_scrNewTimer);

    // NULL screen variables
    uic_scrTimer = NULL;
    ui_scrNewTimer = NULL;
    ui_lblTempNewHeader = NULL;
    ui_contTempNewTimer = NULL;
    ui_rollTempNewMinDec = NULL;
    ui_rollTempNewMin = NULL;
    ui_lblTempNewTimer = NULL;
    ui_contTempNewTimer2 = NULL;
    ui_btnTempNewTimer03 = NULL;
    ui_lblTempNewTimer03 = NULL;
    ui_btnTempNewTimer06 = NULL;
    ui_lblTempNewTimer06 = NULL;
    ui_btnTempNewTimer07 = NULL;
    ui_lblTempNewTimer07 = NULL;
    ui_btnTempNewTimer08 = NULL;
    ui_lblTempNewTimer08 = NULL;
    ui_contTempNewTimer03 = NULL;
    ui_btnTempNewOK = NULL;
    ui_lblTempNewOK = NULL;
    ui_btnTempNewCancel = NULL;
    ui_lblTempNewCancel = NULL;

}
