// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: esp32-kitchen-timer

#include "ui.h"

lv_obj_t * ui_scrHome = NULL;
lv_obj_t * ui_panHomeHeader = NULL;
lv_obj_t * ui_imgHomeHome = NULL;
lv_obj_t * ui_lblHomeHeader = NULL;
lv_obj_t * ui_imgHomeHeaderWifi = NULL;
lv_obj_t * ui_tabHomeAll = NULL;
lv_obj_t * ui_TabEntrada = NULL;
lv_obj_t * ui_contHomeEntradaPasillo = NULL;
lv_obj_t * ui_contHomeEntradaTemp = NULL;
lv_obj_t * ui_imgHomeEntradaTemp = NULL;
lv_obj_t * ui_lblHomeEntradaTemp = NULL;
lv_obj_t * ui_contHomeEntradaHumidity = NULL;
lv_obj_t * ui_imgHomeEntradaHumidity = NULL;
lv_obj_t * ui_lblHomeEntradaHumidity = NULL;
lv_obj_t * ui_contHomeEntradaTime = NULL;
lv_obj_t * ui_imgHomeEntradaTime = NULL;
lv_obj_t * ui_lblHomeEntradaTime = NULL;
lv_obj_t * ui_contHomeEntrada = NULL;
lv_obj_t * ui_contHomeEntradaLight = NULL;
lv_obj_t * ui_lblHomeEntradaLight = NULL;
lv_obj_t * ui_contHomeEntradaLight1 = NULL;
lv_obj_t * ui_arcHomeEntradaLight = NULL;
lv_obj_t * ui_imgHomeEntradaLight = NULL;
lv_obj_t * ui_contHomeEntradaDish = NULL;
lv_obj_t * ui_lblHomeEntradaDish = NULL;
lv_obj_t * ui_imgHomeEntradaDish = NULL;
lv_obj_t * ui_swHomeEntradaDish = NULL;
lv_obj_t * ui_TabTerraza = NULL;
lv_obj_t * ui_contHomeTerrazaWeather = NULL;
lv_obj_t * ui_contHomeTerrazaTemp = NULL;
lv_obj_t * ui_imgHomeTerrazaTemp = NULL;
lv_obj_t * ui_lblHomeTerrazaTemp = NULL;
lv_obj_t * ui_contHomeTerrazaTime = NULL;
lv_obj_t * ui_imgHomeTerrazaTime = NULL;
lv_obj_t * ui_lblHomeTerrazaTime = NULL;
lv_obj_t * ui_contHomeTerraza = NULL;
lv_obj_t * ui_contHomeTerrazaRiego = NULL;
lv_obj_t * ui_lblHomeTerrazaRiego = NULL;
lv_obj_t * ui_contHomeTerrazaRiego1 = NULL;
lv_obj_t * ui_lblHomeTerrazaRiegoTime = NULL;
lv_obj_t * ui_arcHomeTerrazaRiego = NULL;
lv_obj_t * ui_imgHomeTerrazaRiego = NULL;
lv_obj_t * ui_lblHomeTerrazaRiegoMin = NULL;
lv_obj_t * ui_swHomeTerrazaRiego = NULL;
lv_obj_t * ui_lblHomeTerrazaRiegoLastOn = NULL;
lv_obj_t * ui_contHomeTerrazaKeyboard = NULL;
lv_obj_t * ui_kbHomeTerraza = NULL;
// event funtions
void ui_event_imgHomeHome(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrMain, LV_SCR_LOAD_ANIM_NONE, 250, 0, &ui_scrMain_screen_init);
    }
}

void ui_event_arcHomeEntradaLight(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    
    if(event_code == LV_EVENT_RELEASED) {
        arcHomeEntradaLightChange(e);
    }
}

void ui_event_swHomeEntradaDish(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        swHomeEntradaDishClick(e);
    }
}

void ui_event_arcHomeTerrazaRiego(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        arcHomeTerrazaRiegoChange(e);
    }
}

void ui_event_swHomeTerrazaRiego(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        swHomeTerrazaRiegoClick(e);
    }
}

// build funtions

void ui_scrHome_screen_init(void)
{
    ui_scrHome = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_scrHome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_scrHome, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panHomeHeader = lv_obj_create(ui_scrHome);
    lv_obj_set_height(ui_panHomeHeader, 40);
    lv_obj_set_width(ui_panHomeHeader, lv_pct(100));
    lv_obj_set_flex_flow(ui_panHomeHeader, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_panHomeHeader, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_panHomeHeader, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_panHomeHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panHomeHeader, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panHomeHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_panHomeHeader, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgHomeHome = lv_imagebutton_create(ui_panHomeHeader);
    lv_imagebutton_set_src(ui_imgHomeHome, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_home_png, NULL);
    lv_imagebutton_set_src(ui_imgHomeHome, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_home_png, NULL);
    lv_obj_set_width(ui_imgHomeHome, 32);
    lv_obj_set_height(ui_imgHomeHome, 32);
    lv_obj_set_align(ui_imgHomeHome, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_imgHomeHome, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_IMAGE_RECOLOR,
                                           _ui_theme_color_colorTimerDef);
    ui_object_set_themeable_style_property(ui_imgHomeHome, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_IMAGE_RECOLOR_OPA,
                                           _ui_theme_alpha_colorTimerDef);

    ui_lblHomeHeader = lv_label_create(ui_panHomeHeader);
    lv_obj_set_width(ui_lblHomeHeader, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblHomeHeader, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblHomeHeader, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_lblHomeHeader, "CASA");
    lv_obj_set_style_pad_left(ui_lblHomeHeader, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblHomeHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblHomeHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblHomeHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgHomeHeaderWifi = lv_image_create(ui_panHomeHeader);
    lv_image_set_src(ui_imgHomeHeaderWifi, &ui_img_wifi_on_png);
    lv_obj_set_width(ui_imgHomeHeaderWifi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgHomeHeaderWifi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imgHomeHeaderWifi, 0);
    lv_obj_set_y(ui_imgHomeHeaderWifi, 7);
    lv_obj_set_align(ui_imgHomeHeaderWifi, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_imgHomeHeaderWifi, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgHomeHeaderWifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_tabHomeAll = lv_tabview_create(ui_scrHome);
    lv_tabview_set_tab_bar_size(ui_tabHomeAll, 50);
    lv_obj_set_height(ui_tabHomeAll, 435);
    lv_obj_set_width(ui_tabHomeAll, lv_pct(100));
    lv_obj_set_align(ui_tabHomeAll, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_remove_flag(ui_tabHomeAll, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_tabHomeAll, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabEntrada = lv_tabview_add_tab(ui_tabHomeAll, "ENTRADA");
    lv_obj_set_flex_flow(ui_TabEntrada, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_TabEntrada, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);

    ui_contHomeEntradaPasillo = lv_obj_create(ui_TabEntrada);
    lv_obj_remove_style_all(ui_contHomeEntradaPasillo);
    lv_obj_set_width(ui_contHomeEntradaPasillo, lv_pct(100));
    lv_obj_set_height(ui_contHomeEntradaPasillo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_contHomeEntradaPasillo, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_contHomeEntradaPasillo, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_contHomeEntradaPasillo, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contHomeEntradaPasillo, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_contHomeEntradaTemp = lv_obj_create(ui_contHomeEntradaPasillo);
    lv_obj_remove_style_all(ui_contHomeEntradaTemp);
    lv_obj_set_width(ui_contHomeEntradaTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_contHomeEntradaTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_contHomeEntradaTemp, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_contHomeEntradaTemp, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_contHomeEntradaTemp, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contHomeEntradaTemp, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgHomeEntradaTemp = lv_image_create(ui_contHomeEntradaTemp);
    lv_image_set_src(ui_imgHomeEntradaTemp, &ui_img_thermo_png);
    lv_obj_set_width(ui_imgHomeEntradaTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgHomeEntradaTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgHomeEntradaTemp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgHomeEntradaTemp, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgHomeEntradaTemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblHomeEntradaTemp = lv_label_create(ui_contHomeEntradaTemp);
    lv_obj_set_width(ui_lblHomeEntradaTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblHomeEntradaTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblHomeEntradaTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblHomeEntradaTemp, "21 C");

    ui_contHomeEntradaHumidity = lv_obj_create(ui_contHomeEntradaPasillo);
    lv_obj_remove_style_all(ui_contHomeEntradaHumidity);
    lv_obj_set_width(ui_contHomeEntradaHumidity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_contHomeEntradaHumidity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_contHomeEntradaHumidity, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_contHomeEntradaHumidity, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_contHomeEntradaHumidity, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contHomeEntradaHumidity, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgHomeEntradaHumidity = lv_image_create(ui_contHomeEntradaHumidity);
    lv_image_set_src(ui_imgHomeEntradaHumidity, &ui_img_drop_png);
    lv_obj_set_width(ui_imgHomeEntradaHumidity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgHomeEntradaHumidity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgHomeEntradaHumidity, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgHomeEntradaHumidity, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgHomeEntradaHumidity, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblHomeEntradaHumidity = lv_label_create(ui_contHomeEntradaHumidity);
    lv_obj_set_width(ui_lblHomeEntradaHumidity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblHomeEntradaHumidity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblHomeEntradaHumidity, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblHomeEntradaHumidity, "50%");

    ui_contHomeEntradaTime = lv_obj_create(ui_contHomeEntradaPasillo);
    lv_obj_remove_style_all(ui_contHomeEntradaTime);
    lv_obj_set_width(ui_contHomeEntradaTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_contHomeEntradaTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_contHomeEntradaTime, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_contHomeEntradaTime, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_contHomeEntradaTime, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contHomeEntradaTime, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgHomeEntradaTime = lv_image_create(ui_contHomeEntradaTime);
    lv_image_set_src(ui_imgHomeEntradaTime, &ui_img_clock_png);
    lv_obj_set_width(ui_imgHomeEntradaTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgHomeEntradaTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgHomeEntradaTime, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgHomeEntradaTime, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgHomeEntradaTime, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblHomeEntradaTime = lv_label_create(ui_contHomeEntradaTime);
    lv_obj_set_width(ui_lblHomeEntradaTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblHomeEntradaTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblHomeEntradaTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblHomeEntradaTime, "19:12");

    ui_contHomeEntrada = lv_obj_create(ui_TabEntrada);
    lv_obj_remove_style_all(ui_contHomeEntrada);
    lv_obj_set_width(ui_contHomeEntrada, lv_pct(100));
    lv_obj_set_height(ui_contHomeEntrada, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_contHomeEntrada, -242);
    lv_obj_set_y(ui_contHomeEntrada, 130);
    lv_obj_set_flex_flow(ui_contHomeEntrada, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_contHomeEntrada, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contHomeEntrada, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_contHomeEntradaLight = lv_obj_create(ui_contHomeEntrada);
    lv_obj_remove_style_all(ui_contHomeEntradaLight);
    lv_obj_set_width(ui_contHomeEntradaLight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_contHomeEntradaLight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_contHomeEntradaLight, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_contHomeEntradaLight, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_contHomeEntradaLight, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contHomeEntradaLight, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblHomeEntradaLight = lv_label_create(ui_contHomeEntradaLight);
    lv_obj_set_width(ui_lblHomeEntradaLight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblHomeEntradaLight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblHomeEntradaLight, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblHomeEntradaLight, "Luz Pasillo");

    ui_contHomeEntradaLight1 = lv_obj_create(ui_contHomeEntradaLight);
    lv_obj_remove_style_all(ui_contHomeEntradaLight1);
    lv_obj_set_width(ui_contHomeEntradaLight1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_contHomeEntradaLight1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_contHomeEntradaLight1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contHomeEntradaLight1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_contHomeEntradaLight1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_contHomeEntradaLight1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_contHomeEntradaLight1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_contHomeEntradaLight1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_arcHomeEntradaLight = lv_arc_create(ui_contHomeEntradaLight1);
    lv_obj_set_width(ui_arcHomeEntradaLight, 200);
    lv_obj_set_height(ui_arcHomeEntradaLight, 200);
    lv_obj_set_align(ui_arcHomeEntradaLight, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_arcHomeEntradaLight, 50);

    ui_imgHomeEntradaLight = lv_image_create(ui_contHomeEntradaLight1);
    lv_image_set_src(ui_imgHomeEntradaLight, &ui_img_lightbulb_png);
    lv_obj_set_width(ui_imgHomeEntradaLight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgHomeEntradaLight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgHomeEntradaLight, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgHomeEntradaLight, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgHomeEntradaLight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_imgHomeEntradaLight, LV_IMAGE_ALIGN_TOP_MID);

    ui_contHomeEntradaDish = lv_obj_create(ui_contHomeEntrada);
    lv_obj_remove_style_all(ui_contHomeEntradaDish);
    lv_obj_set_width(ui_contHomeEntradaDish, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_contHomeEntradaDish, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_contHomeEntradaDish, -242);
    lv_obj_set_y(ui_contHomeEntradaDish, 130);
    lv_obj_set_flex_flow(ui_contHomeEntradaDish, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_contHomeEntradaDish, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_contHomeEntradaDish, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_contHomeEntradaDish, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_contHomeEntradaDish, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblHomeEntradaDish = lv_label_create(ui_contHomeEntradaDish);
    lv_obj_set_width(ui_lblHomeEntradaDish, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblHomeEntradaDish, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblHomeEntradaDish, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblHomeEntradaDish, "Lavaplatos");

    ui_imgHomeEntradaDish = lv_imagebutton_create(ui_contHomeEntradaDish);
    lv_imagebutton_set_src(ui_imgHomeEntradaDish, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_laundry_png, NULL);
    lv_obj_set_width(ui_imgHomeEntradaDish, 48);
    lv_obj_set_height(ui_imgHomeEntradaDish, 48);
    lv_obj_set_align(ui_imgHomeEntradaDish, LV_ALIGN_CENTER);

    ui_swHomeEntradaDish = lv_switch_create(ui_contHomeEntradaDish);
    lv_obj_set_width(ui_swHomeEntradaDish, 50);
    lv_obj_set_height(ui_swHomeEntradaDish, 25);
    lv_obj_set_align(ui_swHomeEntradaDish, LV_ALIGN_CENTER);

    ui_TabTerraza = lv_tabview_add_tab(ui_tabHomeAll, "TERRAZA");
    lv_obj_set_flex_flow(ui_TabTerraza, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_TabTerraza, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

    ui_contHomeTerrazaWeather = lv_obj_create(ui_TabTerraza);
    lv_obj_remove_style_all(ui_contHomeTerrazaWeather);
    lv_obj_set_width(ui_contHomeTerrazaWeather, lv_pct(100));
    lv_obj_set_height(ui_contHomeTerrazaWeather, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_contHomeTerrazaWeather, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_contHomeTerrazaWeather, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_contHomeTerrazaWeather, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contHomeTerrazaWeather, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_contHomeTerrazaTemp = lv_obj_create(ui_contHomeTerrazaWeather);
    lv_obj_remove_style_all(ui_contHomeTerrazaTemp);
    lv_obj_set_width(ui_contHomeTerrazaTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_contHomeTerrazaTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_contHomeTerrazaTemp, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_contHomeTerrazaTemp, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_contHomeTerrazaTemp, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contHomeTerrazaTemp, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgHomeTerrazaTemp = lv_image_create(ui_contHomeTerrazaTemp);
    lv_image_set_src(ui_imgHomeTerrazaTemp, &ui_img_thermo_png);
    lv_obj_set_width(ui_imgHomeTerrazaTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgHomeTerrazaTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgHomeTerrazaTemp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgHomeTerrazaTemp, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgHomeTerrazaTemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblHomeTerrazaTemp = lv_label_create(ui_contHomeTerrazaTemp);
    lv_obj_set_width(ui_lblHomeTerrazaTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblHomeTerrazaTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblHomeTerrazaTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblHomeTerrazaTemp, "21 C");

    ui_contHomeTerrazaTime = lv_obj_create(ui_contHomeTerrazaWeather);
    lv_obj_remove_style_all(ui_contHomeTerrazaTime);
    lv_obj_set_width(ui_contHomeTerrazaTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_contHomeTerrazaTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_contHomeTerrazaTime, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_contHomeTerrazaTime, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_contHomeTerrazaTime, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contHomeTerrazaTime, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgHomeTerrazaTime = lv_image_create(ui_contHomeTerrazaTime);
    lv_image_set_src(ui_imgHomeTerrazaTime, &ui_img_clock_png);
    lv_obj_set_width(ui_imgHomeTerrazaTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgHomeTerrazaTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgHomeTerrazaTime, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgHomeTerrazaTime, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgHomeTerrazaTime, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblHomeTerrazaTime = lv_label_create(ui_contHomeTerrazaTime);
    lv_obj_set_width(ui_lblHomeTerrazaTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblHomeTerrazaTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblHomeTerrazaTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblHomeTerrazaTime, "19:12");

    ui_contHomeTerraza = lv_obj_create(ui_TabTerraza);
    lv_obj_remove_style_all(ui_contHomeTerraza);
    lv_obj_set_width(ui_contHomeTerraza, lv_pct(100));
    lv_obj_set_height(ui_contHomeTerraza, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_contHomeTerraza, -242);
    lv_obj_set_y(ui_contHomeTerraza, 130);
    lv_obj_set_flex_flow(ui_contHomeTerraza, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_contHomeTerraza, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contHomeTerraza, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_contHomeTerrazaRiego = lv_obj_create(ui_contHomeTerraza);
    lv_obj_remove_style_all(ui_contHomeTerrazaRiego);
    lv_obj_set_height(ui_contHomeTerrazaRiego, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_contHomeTerrazaRiego, 1);
    lv_obj_set_align(ui_contHomeTerrazaRiego, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_contHomeTerrazaRiego, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_contHomeTerrazaRiego, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contHomeTerrazaRiego, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_contHomeTerrazaRiego, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_contHomeTerrazaRiego, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblHomeTerrazaRiego = lv_label_create(ui_contHomeTerrazaRiego);
    lv_obj_set_width(ui_lblHomeTerrazaRiego, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblHomeTerrazaRiego, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblHomeTerrazaRiego, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblHomeTerrazaRiego, "Riego");

    ui_contHomeTerrazaRiego1 = lv_obj_create(ui_contHomeTerrazaRiego);
    lv_obj_remove_style_all(ui_contHomeTerrazaRiego1);
    lv_obj_set_width(ui_contHomeTerrazaRiego1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_contHomeTerrazaRiego1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_contHomeTerrazaRiego1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contHomeTerrazaRiego1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblHomeTerrazaRiegoTime = lv_label_create(ui_contHomeTerrazaRiego1);
    lv_obj_set_width(ui_lblHomeTerrazaRiegoTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblHomeTerrazaRiegoTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblHomeTerrazaRiegoTime, 0);
    lv_obj_set_y(ui_lblHomeTerrazaRiegoTime, 40);
    lv_obj_set_align(ui_lblHomeTerrazaRiegoTime, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblHomeTerrazaRiegoTime, "21:00");

    ui_arcHomeTerrazaRiego = lv_arc_create(ui_contHomeTerrazaRiego1);
    lv_obj_set_width(ui_arcHomeTerrazaRiego, 200);
    lv_obj_set_height(ui_arcHomeTerrazaRiego, 200);
    lv_obj_set_align(ui_arcHomeTerrazaRiego, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_arcHomeTerrazaRiego, 1, 10);
    lv_arc_set_value(ui_arcHomeTerrazaRiego, 2);

    ui_imgHomeTerrazaRiego = lv_image_create(ui_contHomeTerrazaRiego1);
    lv_image_set_src(ui_imgHomeTerrazaRiego, &ui_img_leaf_png);
    lv_obj_set_width(ui_imgHomeTerrazaRiego, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgHomeTerrazaRiego, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgHomeTerrazaRiego, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgHomeTerrazaRiego, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgHomeTerrazaRiego, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_imgHomeTerrazaRiego, LV_IMAGE_ALIGN_TOP_MID);

    ui_lblHomeTerrazaRiegoMin = lv_label_create(ui_contHomeTerrazaRiego1);
    lv_obj_set_width(ui_lblHomeTerrazaRiegoMin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblHomeTerrazaRiegoMin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblHomeTerrazaRiegoMin, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblHomeTerrazaRiegoMin, "2 min");
    lv_obj_set_style_pad_left(ui_lblHomeTerrazaRiegoMin, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblHomeTerrazaRiegoMin, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblHomeTerrazaRiegoMin, 135, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblHomeTerrazaRiegoMin, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_swHomeTerrazaRiego = lv_switch_create(ui_contHomeTerrazaRiego1);
    lv_obj_set_width(ui_swHomeTerrazaRiego, 50);
    lv_obj_set_height(ui_swHomeTerrazaRiego, 25);
    lv_obj_set_align(ui_swHomeTerrazaRiego, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_state(ui_swHomeTerrazaRiego, LV_STATE_CHECKED);       /// States

    ui_lblHomeTerrazaRiegoLastOn = lv_label_create(ui_contHomeTerrazaRiego);
    lv_obj_set_width(ui_lblHomeTerrazaRiegoLastOn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblHomeTerrazaRiegoLastOn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblHomeTerrazaRiegoLastOn, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblHomeTerrazaRiegoLastOn, "2025-12-22 21:00");

    ui_contHomeTerrazaKeyboard = lv_obj_create(ui_contHomeTerraza);
    lv_obj_remove_style_all(ui_contHomeTerrazaKeyboard);
    lv_obj_set_height(ui_contHomeTerrazaKeyboard, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_contHomeTerrazaKeyboard, 2);
    lv_obj_set_align(ui_contHomeTerrazaKeyboard, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_contHomeTerrazaKeyboard, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_contHomeTerrazaKeyboard, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_kbHomeTerraza = lv_keyboard_create(ui_contHomeTerrazaKeyboard);
    lv_keyboard_set_mode(ui_kbHomeTerraza, LV_KEYBOARD_MODE_USER_1);
    lv_obj_set_height(ui_kbHomeTerraza, 250);
    lv_obj_set_width(ui_kbHomeTerraza, lv_pct(100));
    lv_obj_set_align(ui_kbHomeTerraza, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_imgHomeHome, ui_event_imgHomeHome, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_arcHomeEntradaLight, ui_event_arcHomeEntradaLight, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_swHomeEntradaDish, ui_event_swHomeEntradaDish, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_arcHomeTerrazaRiego, ui_event_arcHomeTerrazaRiego, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_swHomeTerrazaRiego, ui_event_swHomeTerrazaRiego, LV_EVENT_ALL, NULL);

}

void ui_scrHome_screen_destroy(void)
{
    if(ui_scrHome) lv_obj_del(ui_scrHome);

    // NULL screen variables
    ui_scrHome = NULL;
    ui_panHomeHeader = NULL;
    ui_imgHomeHome = NULL;
    ui_lblHomeHeader = NULL;
    ui_imgHomeHeaderWifi = NULL;
    ui_tabHomeAll = NULL;
    ui_TabEntrada = NULL;
    ui_contHomeEntradaPasillo = NULL;
    ui_contHomeEntradaTemp = NULL;
    ui_imgHomeEntradaTemp = NULL;
    ui_lblHomeEntradaTemp = NULL;
    ui_contHomeEntradaHumidity = NULL;
    ui_imgHomeEntradaHumidity = NULL;
    ui_lblHomeEntradaHumidity = NULL;
    ui_contHomeEntradaTime = NULL;
    ui_imgHomeEntradaTime = NULL;
    ui_lblHomeEntradaTime = NULL;
    ui_contHomeEntrada = NULL;
    ui_contHomeEntradaLight = NULL;
    ui_lblHomeEntradaLight = NULL;
    ui_contHomeEntradaLight1 = NULL;
    ui_arcHomeEntradaLight = NULL;
    ui_imgHomeEntradaLight = NULL;
    ui_contHomeEntradaDish = NULL;
    ui_lblHomeEntradaDish = NULL;
    ui_imgHomeEntradaDish = NULL;
    ui_swHomeEntradaDish = NULL;
    ui_TabTerraza = NULL;
    ui_contHomeTerrazaWeather = NULL;
    ui_contHomeTerrazaTemp = NULL;
    ui_imgHomeTerrazaTemp = NULL;
    ui_lblHomeTerrazaTemp = NULL;
    ui_contHomeTerrazaTime = NULL;
    ui_imgHomeTerrazaTime = NULL;
    ui_lblHomeTerrazaTime = NULL;
    ui_contHomeTerraza = NULL;
    ui_contHomeTerrazaRiego = NULL;
    ui_lblHomeTerrazaRiego = NULL;
    ui_contHomeTerrazaRiego1 = NULL;
    ui_lblHomeTerrazaRiegoTime = NULL;
    ui_arcHomeTerrazaRiego = NULL;
    ui_imgHomeTerrazaRiego = NULL;
    ui_lblHomeTerrazaRiegoMin = NULL;
    ui_swHomeTerrazaRiego = NULL;
    ui_lblHomeTerrazaRiegoLastOn = NULL;
    ui_contHomeTerrazaKeyboard = NULL;
    ui_kbHomeTerraza = NULL;

}
