// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: esp32-kitchen-timer

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_colorShadow[1] = {0x2095F6};
const ui_theme_variable_t _ui_theme_alpha_colorShadow[1] = {255};

const ui_theme_variable_t _ui_theme_color_colorMainicons[1] = {0xFFFFFF};
const ui_theme_variable_t _ui_theme_alpha_colorMainicons[1] = {255};

const ui_theme_variable_t _ui_theme_color_colorTimerDef[1] = {0x2095F6};
const ui_theme_variable_t _ui_theme_alpha_colorTimerDef[1] = {255};

const ui_theme_variable_t _ui_theme_color_colorTimerOut[1] = {0xC50000};
const ui_theme_variable_t _ui_theme_alpha_colorTimerOut[1] = {255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

