// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: esp32-kitchen-timer

#ifndef _ESP32_KITCHEN_TIMER_UI_H
#define _ESP32_KITCHEN_TIMER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

///////////////////// SCREENS ////////////////////

#include "ui_scrMain.h"
#include "ui_scrTimers.h"
#include "ui_scrNewTimer.h"
#include "ui_scrHome.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_background_png);    // assets/background.png
LV_IMG_DECLARE(ui_img_home_big_png);    // assets/home_big.png
LV_IMG_DECLARE(ui_img_calendar_png);    // assets/calendar.png
LV_IMG_DECLARE(ui_img_timer_png);    // assets/timer.png
LV_IMG_DECLARE(ui_img_sun_png);    // assets/sun.png
LV_IMG_DECLARE(ui_img_thermo_png);    // assets/thermo.png
LV_IMG_DECLARE(ui_img_drop_png);    // assets/drop.png
LV_IMG_DECLARE(ui_img_wind_png);    // assets/wind.png
LV_IMG_DECLARE(ui_img_sunrise_png);    // assets/sunrise.png
LV_IMG_DECLARE(ui_img_moon_png);    // assets/moon.png
LV_IMG_DECLARE(ui_img_home_png);    // assets/home.png
LV_IMG_DECLARE(ui_img_volume_mid_png);    // assets/volume_mid.png
LV_IMG_DECLARE(ui_img_hourglass_bottom_png);    // assets/hourglass_bottom.png
LV_IMG_DECLARE(ui_img_pause_png);    // assets/pause.png
LV_IMG_DECLARE(ui_img_stop_png);    // assets/stop.png
LV_IMG_DECLARE(ui_img_wifi_on_png);    // assets/wifi_on.png
LV_IMG_DECLARE(ui_img_clock_png);    // assets/clock.png
LV_IMG_DECLARE(ui_img_lightbulb_png);    // assets/lightbulb.png
LV_IMG_DECLARE(ui_img_laundry_png);    // assets/laundry.png
LV_IMG_DECLARE(ui_img_leaf_png);    // assets/leaf.png
LV_IMG_DECLARE(ui_img_cloud_png);    // assets/cloud.png
LV_IMG_DECLARE(ui_img_cloudy_png);    // assets/cloudy.png
LV_IMG_DECLARE(ui_img_fog_png);    // assets/fog.png
LV_IMG_DECLARE(ui_img_lightning_png);    // assets/lightning.png
LV_IMG_DECLARE(ui_img_play_png);    // assets/play.png
LV_IMG_DECLARE(ui_img_rainy_png);    // assets/rainy.png
LV_IMG_DECLARE(ui_img_rainy_hard_png);    // assets/rainy_hard.png
LV_IMG_DECLARE(ui_img_snowy_png);    // assets/snowy.png
LV_IMG_DECLARE(ui_img_volume_low_png);    // assets/volume_low.png
LV_IMG_DECLARE(ui_img_volume_off_png);    // assets/volume_off.png
LV_IMG_DECLARE(ui_img_volume_up_png);    // assets/volume_up.png
LV_IMG_DECLARE(ui_img_wifi_error_png);    // assets/wifi_error.png
LV_IMG_DECLARE(ui_img_wifi_off_png);    // assets/wifi_off.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
