// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: esp32-kitchen-timer

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void imgTempTemp1AddChronoClick(lv_event_t * e);
void imgTempTemp1PlayClick(lv_event_t * e);
void imgTempTemp1StopClick(lv_event_t * e);
void imgTempTemp2AddChronoClick(lv_event_t * e);
void imgTempTemp2PlayClick(lv_event_t * e);
void imgTempTemp2StopClick(lv_event_t * e);
void imgTempTemp3AddChronoClick(lv_event_t * e);
void imgTempTemp3PlayClick(lv_event_t * e);
void imgTempTemp3StopClick(lv_event_t * e);
void imgTempTemp4AddChronoClick(lv_event_t * e);
void imgTempTemp4PlayClick(lv_event_t * e);
void imgTempTemp4StopClick(lv_event_t * e);
void rollSoundThemeChanged(lv_event_t * e);
void sldTempSoundVolumeChange(lv_event_t * e);
void sldTempSoundVolumeRelease(lv_event_t * e);
void btnTempNewOKClick(lv_event_t * e);
void arcHomeEntradaLightChange(lv_event_t * e);
void swHomeEntradaDishClick(lv_event_t * e);
void arcHomeTerrazaRiegoChange(lv_event_t * e);
void swHomeTerrazaRiegoClick(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
