// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: esp32-kitchen-timer

#ifndef UI_SCRMAIN_H
#define UI_SCRMAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrMain
extern void ui_scrMain_screen_init(void);
extern void ui_scrMain_screen_destroy(void);
extern lv_obj_t * ui_scrMain;
extern lv_obj_t * ui_panMainHeader;
extern void ui_event_imgMainHome(lv_event_t * e);
extern lv_obj_t * ui_imgMainHome;
extern void ui_event_imgMainCalendar(lv_event_t * e);
extern lv_obj_t * ui_imgMainCalendar;
extern void ui_event_imgMainTimer(lv_event_t * e);
extern lv_obj_t * ui_imgMainTimer;
extern lv_obj_t * ui_contMain01;
extern lv_obj_t * ui_contMainWeather01;
extern lv_obj_t * ui_imgMainSeeing;
extern lv_obj_t * ui_imgMainForecast;
extern lv_obj_t * ui_lblMainForecast;
extern lv_obj_t * ui_lblMainTime;
extern lv_obj_t * ui_lblMainDate;
extern lv_obj_t * ui_contMainWeather02;
extern lv_obj_t * ui_contMainTemp;
extern lv_obj_t * ui_imgMainTemp;
extern lv_obj_t * ui_lblMainTemp;
extern lv_obj_t * ui_contMainHumidity;
extern lv_obj_t * ui_imgMainHumidity;
extern lv_obj_t * ui_lblMainHumidity;
extern lv_obj_t * ui_contMainWind;
extern lv_obj_t * ui_imgMainWind;
extern lv_obj_t * ui_lblMainWind;
extern lv_obj_t * ui_contMainSun;
extern lv_obj_t * ui_contMainSunrise;
extern lv_obj_t * ui_imgMainSunrise;
extern lv_obj_t * ui_lblMainSunrise;
extern lv_obj_t * ui_contMainSunset;
extern lv_obj_t * ui_imgMainSunset;
extern lv_obj_t * ui_lblMainSunset;
extern lv_obj_t * ui_calMain;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

