// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: esp32-kitchen-timer

#ifndef UI_SCRNEWTIMER_H
#define UI_SCRNEWTIMER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrNewTimer
extern void ui_scrNewTimer_screen_init(void);
extern void ui_scrNewTimer_screen_destroy(void);
extern lv_obj_t * ui_scrNewTimer;
extern lv_obj_t * ui_lblTempNewHeader;
extern lv_obj_t * ui_contTempNewTimer;
extern lv_obj_t * ui_rollTempNewMinDec;
extern lv_obj_t * ui_rollTempNewMin;
extern lv_obj_t * ui_lblTempNewTimer;
extern lv_obj_t * ui_contTempNewTimer2;
extern void ui_event_btnTempNewTimer03(lv_event_t * e);
extern lv_obj_t * ui_btnTempNewTimer03;
extern lv_obj_t * ui_lblTempNewTimer03;
extern void ui_event_btnTempNewTimer06(lv_event_t * e);
extern lv_obj_t * ui_btnTempNewTimer06;
extern lv_obj_t * ui_lblTempNewTimer06;
extern void ui_event_btnTempNewTimer07(lv_event_t * e);
extern lv_obj_t * ui_btnTempNewTimer07;
extern lv_obj_t * ui_lblTempNewTimer07;
extern void ui_event_btnTempNewTimer08(lv_event_t * e);
extern lv_obj_t * ui_btnTempNewTimer08;
extern lv_obj_t * ui_lblTempNewTimer08;
extern lv_obj_t * ui_contTempNewTimer03;
extern void ui_event_btnTempNewOK(lv_event_t * e);
extern lv_obj_t * ui_btnTempNewOK;
extern lv_obj_t * ui_lblTempNewOK;
extern void ui_event_btnTempNewCancel(lv_event_t * e);
extern lv_obj_t * ui_btnTempNewCancel;
extern lv_obj_t * ui_lblTempNewCancel;
// CUSTOM VARIABLES
extern lv_obj_t * uic_scrTimer;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

