// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: esp32-kitchen-timer

#ifndef UI_SCRTIMERS_H
#define UI_SCRTIMERS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrTimers
extern void ui_scrTimers_screen_init(void);
extern void ui_scrTimers_screen_destroy(void);
extern lv_obj_t * ui_scrTimers;
extern lv_obj_t * ui_panTempHeader;
extern void ui_event_imgTempHome(lv_event_t * e);
extern lv_obj_t * ui_imgTempHome;
extern lv_obj_t * ui_lblTempHeader;
extern void ui_event_imgTempHeaderVol(lv_event_t * e);
extern lv_obj_t * ui_imgTempHeaderVol;
extern lv_obj_t * ui_contTempAll;
extern lv_obj_t * ui_contTempRow1;
extern lv_obj_t * ui_contTempTemp1;
extern lv_obj_t * ui_lblTempTimer1Time;
extern lv_obj_t * ui_lblTempTimer1Count;
extern lv_obj_t * ui_imgTempTimer1Chrono;
extern lv_obj_t * ui_panTempTemp1Add;
extern void ui_event_imgTempTemp1AddTimer(lv_event_t * e);
extern lv_obj_t * ui_imgTempTemp1AddTimer;
extern void ui_event_imgTempTemp1AddChrono(lv_event_t * e);
extern lv_obj_t * ui_imgTempTemp1AddChrono;
extern lv_obj_t * ui_panTempTemp1Control;
extern void ui_event_imgTempTemp1Play(lv_event_t * e);
extern lv_obj_t * ui_imgTempTemp1Play;
extern void ui_event_imgTempTemp1Stop(lv_event_t * e);
extern lv_obj_t * ui_imgTempTemp1Stop;
extern lv_obj_t * ui_contTempTemp2;
extern lv_obj_t * ui_lblTempTimer2Time;
extern lv_obj_t * ui_lblTempTimer2Count;
extern lv_obj_t * ui_imgTempTimer2Chrono;
extern lv_obj_t * ui_panTempTemp2Add;
extern void ui_event_imgTempTemp2AddTimer(lv_event_t * e);
extern lv_obj_t * ui_imgTempTemp2AddTimer;
extern void ui_event_imgTempTemp2AddChrono(lv_event_t * e);
extern lv_obj_t * ui_imgTempTemp2AddChrono;
extern lv_obj_t * ui_panTempTemp2Control;
extern void ui_event_imgTempTemp2Play(lv_event_t * e);
extern lv_obj_t * ui_imgTempTemp2Play;
extern void ui_event_imgTempTemp2Stop(lv_event_t * e);
extern lv_obj_t * ui_imgTempTemp2Stop;
extern lv_obj_t * ui_contTempRow2;
extern lv_obj_t * ui_contTempTemp3;
extern lv_obj_t * ui_lblTempTimer3Time;
extern lv_obj_t * ui_lblTempTimer3Count;
extern lv_obj_t * ui_imgTempTimer3Chrono;
extern lv_obj_t * ui_panTempTemp3Add;
extern void ui_event_imgTempTemp3AddTimer(lv_event_t * e);
extern lv_obj_t * ui_imgTempTemp3AddTimer;
extern void ui_event_imgTempTemp3AddChrono(lv_event_t * e);
extern lv_obj_t * ui_imgTempTemp3AddChrono;
extern lv_obj_t * ui_panTempTemp3Control;
extern void ui_event_imgTempTemp3Play(lv_event_t * e);
extern lv_obj_t * ui_imgTempTemp3Play;
extern void ui_event_imgTempTemp3Stop(lv_event_t * e);
extern lv_obj_t * ui_imgTempTemp3Stop;
extern lv_obj_t * ui_contTempTemp4;
extern lv_obj_t * ui_lblTempTimer4Time;
extern lv_obj_t * ui_lblTempTimer4Count;
extern lv_obj_t * ui_imgTempTimer4Chrono;
extern lv_obj_t * ui_panTempTemp4Add;
extern void ui_event_imgTempTemp4AddTimer(lv_event_t * e);
extern lv_obj_t * ui_imgTempTemp4AddTimer;
extern void ui_event_imgTempTemp4AddChrono(lv_event_t * e);
extern lv_obj_t * ui_imgTempTemp4AddChrono;
extern lv_obj_t * ui_panTempTemp4Control;
extern void ui_event_imgTempTemp4Play(lv_event_t * e);
extern lv_obj_t * ui_imgTempTemp4Play;
extern void ui_event_imgTempTemp4Stop(lv_event_t * e);
extern lv_obj_t * ui_imgTempTemp4Stop;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

