// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: esp32-kitchen-timer

#ifndef UI_SCRHOME_H
#define UI_SCRHOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrHome
extern void ui_scrHome_screen_init(void);
extern void ui_scrHome_screen_destroy(void);
extern lv_obj_t * ui_scrHome;
extern lv_obj_t * ui_panHomeHeader;
extern void ui_event_imgHomeHome(lv_event_t * e);
extern lv_obj_t * ui_imgHomeHome;
extern lv_obj_t * ui_lblHomeHeader;
extern lv_obj_t * ui_imgHomeHeaderWifi;
extern lv_obj_t * ui_tabHomeAll;
extern lv_obj_t * ui_TabEntrada;
extern lv_obj_t * ui_contHomeEntradaPasillo;
extern lv_obj_t * ui_contHomeEntradaTemp;
extern lv_obj_t * ui_imgHomeEntradaTemp;
extern lv_obj_t * ui_lblHomeEntradaTemp;
extern lv_obj_t * ui_contHomeEntradaHumidity;
extern lv_obj_t * ui_imgHomeEntradaHumidity;
extern lv_obj_t * ui_lblHomeEntradaHumidity;
extern lv_obj_t * ui_contHomeEntradaTime;
extern lv_obj_t * ui_imgHomeEntradaTime;
extern lv_obj_t * ui_lblHomeEntradaTime;
extern lv_obj_t * ui_contHomeEntrada;
extern lv_obj_t * ui_contHomeEntradaLight;
extern lv_obj_t * ui_lblHomeEntradaLight;
extern lv_obj_t * ui_contHomeEntradaLight1;
extern void ui_event_arcHomeEntradaLight(lv_event_t * e);
extern lv_obj_t * ui_arcHomeEntradaLight;
extern lv_obj_t * ui_imgHomeEntradaLight;
extern lv_obj_t * ui_contHomeEntradaDish;
extern lv_obj_t * ui_lblHomeEntradaDish;
extern lv_obj_t * ui_imgHomeEntradaDish;
extern void ui_event_swHomeEntradaDish(lv_event_t * e);
extern lv_obj_t * ui_swHomeEntradaDish;
extern lv_obj_t * ui_TabTerraza;
extern lv_obj_t * ui_contHomeTerrazaWeather;
extern lv_obj_t * ui_contHomeTerrazaTemp;
extern lv_obj_t * ui_imgHomeTerrazaTemp;
extern lv_obj_t * ui_lblHomeTerrazaTemp;
extern lv_obj_t * ui_contHomeTerrazaTime;
extern lv_obj_t * ui_imgHomeTerrazaTime;
extern lv_obj_t * ui_lblHomeTerrazaTime;
extern lv_obj_t * ui_contHomeTerraza;
extern lv_obj_t * ui_contHomeTerrazaRiego;
extern lv_obj_t * ui_lblHomeTerrazaRiego;
extern lv_obj_t * ui_contHomeTerrazaRiego1;
extern lv_obj_t * ui_lblHomeTerrazaRiegoTime;
extern void ui_event_arcHomeTerrazaRiego(lv_event_t * e);
extern lv_obj_t * ui_arcHomeTerrazaRiego;
extern lv_obj_t * ui_imgHomeTerrazaRiego;
extern lv_obj_t * ui_lblHomeTerrazaRiegoMin;
extern void ui_event_swHomeTerrazaRiego(lv_event_t * e);
extern lv_obj_t * ui_swHomeTerrazaRiego;
extern lv_obj_t * ui_lblHomeTerrazaRiegoLastOn;
extern lv_obj_t * ui_contHomeTerrazaKeyboard;
extern lv_obj_t * ui_kbHomeTerraza;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

