// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: esp32-kitchen-timer

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_COLORSHADOW 0
#define UI_THEME_COLOR_COLORMAINICONS 1
#define UI_THEME_COLOR_COLORTIMERDEF 2
#define UI_THEME_COLOR_COLORTIMEROUT 3

#define UI_THEME_DEFAULT 0

extern const ui_theme_variable_t _ui_theme_color_colorShadow[1];
extern const ui_theme_variable_t _ui_theme_alpha_colorShadow[1];

extern const ui_theme_variable_t _ui_theme_color_colorMainicons[1];
extern const ui_theme_variable_t _ui_theme_alpha_colorMainicons[1];

extern const ui_theme_variable_t _ui_theme_color_colorTimerDef[1];
extern const ui_theme_variable_t _ui_theme_alpha_colorTimerDef[1];

extern const ui_theme_variable_t _ui_theme_color_colorTimerOut[1];
extern const ui_theme_variable_t _ui_theme_alpha_colorTimerOut[1];

extern const uint32_t * ui_theme_colors[1];
extern const uint8_t * ui_theme_alphas[1];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
