// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: esp32-kitchen-timer

#include "ui.h"
#include "events.h"

void imgTempTemp1AddChronoClick(lv_event_t * e)
{
	lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        evTempAddChronoClick(1);
    }

}

void imgTempTemp1PlayClick(lv_event_t * e)
{
	lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        evTempPlayClick (1);
    }

}

void imgTempTemp1StopClick(lv_event_t * e)
{
	lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        evTempStopClick (1);
    }

}

void imgTempTemp2AddChronoClick(lv_event_t * e)
{
	lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        evTempAddChronoClick(2);
    }
}

void imgTempTemp2PlayClick(lv_event_t * e)
{
	lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        evTempPlayClick (2);
    }
}

void imgTempTemp2StopClick(lv_event_t * e)
{
	lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        evTempStopClick (2);
    }
}

void imgTempTemp3AddChronoClick(lv_event_t * e)
{
	lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        evTempAddChronoClick(3);
    }
}

void imgTempTemp3PlayClick(lv_event_t * e)
{
	lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        evTempPlayClick (3);
    }
}

void imgTempTemp3StopClick(lv_event_t * e)
{
	lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        evTempStopClick (3);
    }
}

void imgTempTemp4AddChronoClick(lv_event_t * e)
{
	lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        evTempAddChronoClick(4);
    }
}

void imgTempTemp4PlayClick(lv_event_t * e)
{
	lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        evTempPlayClick (4);
    }
}

void imgTempTemp4StopClick(lv_event_t * e)
{
	lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        evTempStopClick (4);
    }
}

void btnTempNewOKClick(lv_event_t * e)
{
	lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        evTempNewOKClick();
    }
}

void arcHomeEntradaLightChange(lv_event_t * e)
{
	lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_RELEASED) {
        evEntradaLightChange();
    }
}

void swHomeEntradaDishClick(lv_event_t * e)
{
	lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        evEntradaDishClick();
    }
}

void arcHomeTerrazaRiegoChange(lv_event_t * e)
{
	lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        evRiegoChange();
    }
}

void swHomeTerrazaRiegoClick(lv_event_t * e)
{
	lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        evTerrazaRiegoClick();
    }
}

void rollSoundThemeChanged(lv_event_t * e)
{
	evSoundThemeChange();
}

void sldTempSoundVolumeChange(lv_event_t * e)
{
	evSoundVolumeChange();
}

void sldTempSoundVolumeRelease(lv_event_t * e)
{
	evSoundVolumeRelease();
}